### ISSUE TITLE
Languages files updated here but not on the Gnome repo

### ISSUE THREAD

**Issue by Lamecarlate** [passingthru67/workspaces-to-dock#101]
### Linux Distribution version

Ubuntu 17.04 

### Gnome Shell version

GNOME Shell 3.24.1

### Extension version or branch

version 42

### Description of the problem

The french translation has been updated in .po files in this Github repo, but the files haven't be compiled to .mo, it seems. In settings popup, I still have "mignatures" instead of "miniatures" (for "thumbnails") even though it's fixed in the .po. Is it possible to recompile languages files and update the extensions.gnome.org repo? Many thanks.

**Comment by passingthru67** [comment]
I'll check into it

**Comment by passingthru67** [comment]
Looks like some of the translation files had errors. I'll have to correct and update the translation files (to the best of my ability) and then recompile them.

**Comment by passingthru67** [comment]
The latest commits fix the translation files but, unfortunately, some of the translations need to be updated.

**Comment by Lamecarlate** [comment]
I'll look into the .po files if you want it (and if it's a language I can understand); which translations need to be updated?

**Comment by passingthru67** [comment]
All of them need to be updated since they predate the latest changes in the preferences. But, the German and Russian translations are in the worst shape.

**Comment by Lamecarlate** [comment]
OK, I'll stick to french ^^' I don't speak a word of russian, and my german college classes are far, far away. Sorry.

**Comment by passingthru67** [comment]
Thanks.

**Comment by passingthru67** [comment]
I'm closing this issue for now. Maybe we'll get some translation help in the future.
