### ISSUE TITLE
Request: change the arrows according to dock position

### ISSUE THREAD

**Issue by Feichtmeier** [passingthru67/workspaces-to-dock#102]
###Linux Distribution version
Ubuntu 16.04

###Gnome Shell version
Gnome 3.20

###Extension version or branch

###Description of the problem
When I use the option to have the workspace dock on the bottom and pres ctrl+alt+arrow left/right the grid that appears shows the arrows as if I would use the dock on the right or left (see the screenshots)

![screenshot from 2017-06-21 14-30-08](https://user-images.githubusercontent.com/15329494/27384233-72afa77c-568e-11e7-800e-e333ecd1385c.png)
![screenshot from 2017-06-21 14-30-37](https://user-images.githubusercontent.com/15329494/27384272-99e8790e-568e-11e7-9ab1-034a1b9c8c65.png)

###Steps to reproduce the problem

**Comment by passingthru67** [comment]
Are you using the default Gnome Shell Adwaita theme or is it a custom theme?

**Comment by Feichtmeier** [comment]
Oh... yes... I use the pop gtk theme from system76. Tried default and there were no arrows anymore. I guess you can close it then :) And I ask the theme devs =)

**Comment by passingthru67** [comment]
Hold up on that. I may have missed something because I only check the dock operation with Adwaita. I'll get back with you after I check through my code.

**Comment by passingthru67** [comment]
After checking the code and gnome-shell.css, I only find the 'ws-switcher-active-up' and 'ws-switcher-active-down' styles. Gnome doesn't seem to provide style classes for ws-switcher left and right. But, if the theme devs want to create a custom workspaces-to-dock.css with these additional style classes, I should be able to incorporate them.

**Comment by Feichtmeier** [comment]
I don't know how to cross link someone from a different repository, otherwise I could open a ticket there or at adapta (which they use for as a base for their gtk theme)

**Comment by passingthru67** [comment]
I've noticed other issues (specific to the workspaces thumbnails) in the adapta theme implementation. I expect someone would have to submit a pull request with the appropriate changes.
