### ISSUE TITLE
[GNOME 3.26 ERROR] No JS module 'separator' found in search path 

### ISSUE THREAD

**Issue by alex285** [passingthru67/workspaces-to-dock#103]
i just give a heads up, that `js/ui/separator.js` was removed with this commit
https://git.gnome.org/browse/gnome-shell/commit/?id=c1eaa8e52d00c70a4fa1f88683a1fa483437b93a

(gnome-shell:3898): Gjs-WARNING **: JS ERROR: Exception in callback for signal: extension-found: ImportError: No JS module 'separator' found in search path
@/home/alex/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:25:7
@/home/alex/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:43:7
@/home/alex/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:20:7

**Comment by alex285** [comment]
i open a PR that moved `separator.js` inside the extension if you want to merge
https://github.com/passingthru67/workspaces-to-dock/pull/104

**Comment by passingthru67** [comment]
Thanks.

**Comment by passingthru67** [comment]
This issue is fixed in the latest commits.
