### ISSUE TITLE
Inactive pixels at the edge of the screen in dock mode

### ISSUE THREAD

**Issue by LuccoJ** [passingthru67/workspaces-to-dock#105]
Fedora Rawhide, GNOME Shell 3.25.3.
Not sure about the version of the extension because right now its preferences won't open... but that's a different issue to report!

I use this extension in a configuration that mostly mirrors the way Dash to Dock works, mainly because this is more compatible with touchscreens, and the workspace switching is secondary to me.
When used as a fixed favorites dock at the left edge of the screen, moving the mouse pointer to the very edge of the screen and then trying to click an icon results in clicking outside the icon (so, no action).
Typically, UI designs ensures that UI items found at the edges/corners of the screen can be clicked by pushing the pointer into the relevant edge/corner, as that's usually much easier than aiming exactly to avoid "dead" pixels.

To reproduce: set the dock to appear on the left edge; enable a favorites bar; set it to appear "inside"; disable autohide; enable "Partial fixed"; try to click an icon by moving the mouse pointer to the far left edge of the screen.
Nothing will happen. Desired behavior: an icon click is triggered.

**Comment by passingthru67** [comment]
A workaround to this issue would be to remove the padding around the shortcut panel icons. Try editing the padding setting (line #114) in workspaces-to-dock.css and set it to 0px. I'll look into making this a future option under preferences.

112 #workspacestodockDock.left.inside .workspacestodock-shortcuts-panel {
113    border-radius: 0 9px 9px 0;
**114    padding: 2px;**
115    spacing: 0px;
116    border-right: 1px;
117}

BTW, workspaces-to-dock.css is located at ~/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/themes/default/workspaces-to-dock.css

**Comment by LuccoJ** [comment]
That works (on Debian testing, since my Fedora Rawhide is currently unable to run most extensions), thanks.

If you decide to include it as an option, I suggest seeing if it can be done in a way that doesn't make the brighter square around the selected icon visually touch the border of the screen, as that is not very pleasant to see.

**Comment by passingthru67** [comment]
The latest commits fix this issue.
