### ISSUE TITLE
Laggy in gnome 3.25.4

### ISSUE THREAD

**Issue by vans163** [passingthru67/workspaces-to-dock#106]
###Linux Distribution version
Fedora Rawhide
Intel Kaby Lake CPU, Laptop.  
Intel GPU.
Wayland

###Gnome Shell version
3.25.4

###Extension version or branch
master with https://github.com/passingthru67/workspaces-to-dock/pull/104

###Description of the problem
The mouse cursor movement and whole desktop gets noticeably laggy and unresponsive.

###Steps to reproduce the problem
Enable the extension

**Comment by passingthru67** [comment]
Please check out the latest commits in master and test again. Let me know if the lag is still present.

**Comment by passingthru67** [comment]
Is this lagging still an issue or has it been resolved?

**Comment by vans163** [comment]
Iv throw away wayland, far far away, so cannot comment. Back to xorg.

**Comment by passingthru67** [comment]
I'll close this issue for now. We can reopen if necessary.
