### ISSUE TITLE
Add an option to only show workspaces-to-dock in the overview

### ISSUE THREAD

**Issue by Paviluf** [passingthru67/workspaces-to-dock#110]
Hello,

I want to use workspaces-to-dock to show applications that are running per virtual desktop in the overview while this feature in not implemented in gnome shell https://bugzilla.gnome.org/show_bug.cgi?id=782272. 

I don't want workspaces-to-dock to be visible on the desktop but only in the overview. So it will be awesome if you can add an option to only show workspaces-to-dock in the overview.

Thanks !

**Comment by passingthru67** [comment]
This functionality already exists (although there was a bug preventing it from working properly that has been fixed for a while). Just disable Autohide and Intellihide and make sure to set 'What should we do with the dock in overview mode' to Show Full. All these options are found under the Behavior tab.

Let me know if this is still a problem.

**Comment by Paviluf** [comment]
Not very straightforward but that work ! Thanks !
