### ISSUE TITLE
Broken under Gnome shell 3.26

### ISSUE THREAD

**Issue by silviobierman** [passingthru67/workspaces-to-dock#112]
###Linux Distribution version
Ubuntu 17.10 (dev branch)

###Gnome Shell version
3.26

###Extension version or branch
v42_3.24

###Description of the problem
Does not work at all. The dock does not appear.

###Steps to reproduce the problem
Install/enable the extension

**Comment by silviobierman** [comment]
The error reads: Import error: no JS module 'separator' found in search path.

**Comment by lexruee** [comment]
@silviobierman 
I guess this issue is already solved on the master branch. See here: https://github.com/passingthru67/workspaces-to-dock/pull/104

**Comment by passingthru67** [comment]
I've got a few commits to make before I upload a new version to extensions.gnome.org site. In the mean time, download and install the master branch. It should work with Gnome 3.26.

**Comment by silviobierman** [comment]
Thanks guys. I could not get the master branch working so I guess I will just wait for the new version.

**Comment by wyqydsyq** [comment]
Any ETA on when it'll be published to the extensions site? I just upgraded my GNOME today to find this plugin broken. Would rather not mess around installing it from a static download then having to change it back to the official one when it's released

**Comment by passingthru67** [comment]
Just submitted it to extensions.gnome.org for review.

**Comment by texjoachim** [comment]
How long does it take to get it reviewed?

**Comment by silviobierman** [comment]
I tested the latest release on Ubuntu 17.10 / Gnome shell 3.26 and have not yet experienced any problems. Works flawlessly so far.
Thank you for the good work!

**Comment by passingthru67** [comment]
@silviobierman, Thanks for the feedback.
@texjoachim, It's hard to say because it depends on how busy the reviewers are. Generally, it takes a week. But, I've had instances where it only took a few days.

**Comment by texjoachim** [comment]
The update is live now!
Great job!
