### ISSUE TITLE
Another issue on Gnome shell 3.26

### ISSUE THREAD

**Issue by silviobierman** [passingthru67/workspaces-to-dock#114]
###Linux Distribution version
Ubuntu 17.10

###Gnome Shell version
3.26.0 (also on recent 3.25.x versions)

###Extension version or branch
master branch

###Description of the problem
This is an intermittent (I have observed this a couple of times a day for the last week) failure where the dock no longer appears. I am running Wayland. Workspaces set to static (6)

The error reads: TypeError: DashToDock.dockManager._allDocks[0] is undefined

###Steps to reproduce the problem
Install/enable the plugin

**Comment by silviobierman** [comment]
I just realized there is some interaction with the DashToDock plugin here. The error is listed as a failure of WorkspacesToDock extension (Alt-F2 -> lg -> Extensions) but the message mentions DashToDock.
I hope that makes more sense to you as it does to me.

**Comment by passingthru67** [comment]
@silviobierman, If you don't mind, would you export your settings so that I can simulate your setup? Just type the following commands in a terminal and copy/paste the results here.

dconf dump /org/gnome/shell/extensions/workspaces-to-dock/
dconf dump /org/gnome/shell/extensions/dash-to-dock/

**Comment by silviobierman** [comment]
No problem, that I can mange:

silvio@mizuno:~$ dconf dump /org/gnome/shell/extensions/workspaces-to-dock/
[/]
primary-monitor=0
customize-thumbnail=true
workspace-caption-items=['spacer:false']
dock-edge-visible=false
hide-dash=true
customize-height=true
intellihide=false
show-shortcuts-panel=false
thumbnail-size=0.20000000000000001
toggle-overview=false
pressure-threshold=10.0
customize-height-option=1
require-pressure-to-show=false
workspace-captions=false
workspace-caption-taskbar-tooltips=false
background-opacity=1.0
top-margin=0.0
silvio@mizuno:~$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
opaque-background=true
custom-theme-running-dots-border-color='#888a85'
shift-click-action='minimize'
shift-middle-click-action='launch'
extend-height=true
dock-fixed=true
custom-theme-running-dots-color='#ffffff'
click-action='cycle-windows'
force-straight-corner=true
show-apps-at-top=true
preferred-monitor=0
multi-monitor=true
scroll-action='cycle-windows'
custom-theme-customize-running-dots=true
custom-theme-running-dots=true
unity-backlit-items=false
dock-position='LEFT'
custom-theme-shrink=true
background-opacity=0.27000000000000002
custom-theme-running-dots-border-width=2
dash-max-icon-size=28
middle-click-action='launch'
icon-size-fixed=true

**Comment by silviobierman** [comment]
Resolved in latest release. Thank you very much!

The extensions website does not yet offer this release, BTW.

**Comment by passingthru67** [comment]
The latest version of Workspaces-to-Dock is currently under review at extensions.gnome.org. It should be available there soon.
