### ISSUE TITLE
Chromium/Chrome windows are invisible (Wayland)

### ISSUE THREAD

**Issue by silviobierman** [passingthru67/workspaces-to-dock#116]
###Linux Distribution version
Ubuntu 17.10

###Gnome Shell version
3.26

###Extension version or branch
v43_3.26

###Description of the problem
Chromium / Chrome windows are not visible in the dock. Only after dragging a window from the overview mode onto a workspace the window is displayed.

###Steps to reproduce the problem
See description.

**Comment by balderclaassen** [comment]
I could not reproduce this bug on Ubuntu 17.04 Gnome 3.24 with either Chrome or Chromium based Vivaldi. 
When you say Chromium/Chrome do you mean you tested both Chrome and Chromium (or a Chromium based browser?)

**Comment by silviobierman** [comment]
I have installed Chromium browser from the Ubuntu repo (chromium-browser) and installed Chrome by downloading and installing the .deb file from Google.
Both browsers show this behavior. The dock shows all my other windows but leaves out the Chrome and Chromium ones.

I have not tried this with 3.24.

**Comment by silviobierman** [comment]
Here is a screenshot.

![screenshot from 2017-09-19 10-55-20](https://user-images.githubusercontent.com/734637/30584155-2e0f11c0-9d29-11e7-9e1b-11c45bd45229.png)

**Comment by passingthru67** [comment]
Are the chromium windows invisible in the default Gnome workspace thumbnails also, or just workspaces-to-dock?

**Comment by passingthru67** [comment]
I just tested with a nightly build of Ubuntu Live 17.10 (Gnome 3.26), but I don't see any issues with Chromium not showing up in the thumbnails. I'm using default settings for workspaces-to-dock. Is there something I'm missing that's preventing me from duplicating the issue?

**Comment by silviobierman** [comment]
I just tried running X instead of Wayland. Then everything is working. So it is only when using Wayland.

**Comment by passingthru67** [comment]
I'm still not able to duplicate the issue even on a newly installed Ubuntu 17.10 running Wayland.

Would you mind exporting your workspaces-to-dock settings? Just open a terminal and type "dconf dump /org/gnome/shell/extensions/workspaces-to-dock/". Then, copy/paste the results here.

Also, are there any particular Gnome Tweek settings I should change?

**Comment by silviobierman** [comment]
Sure. Here are my settings:

 dconf dump /org/gnome/shell/extensions/workspaces-to-dock/
[/]
primary-monitor=0
customize-thumbnail=true
workspace-caption-items=['spacer:false']
dock-edge-visible=false
hide-dash=true
customize-height=true
intellihide=false
show-shortcuts-panel=false
thumbnail-size=0.20000000000000001
toggle-overview=false
pressure-threshold=10.0
customize-height-option=1
require-pressure-to-show=false
workspace-captions=false
workspace-caption-taskbar-tooltips=false
background-opacity=1.0
top-margin=0.0

**Comment by silviobierman** [comment]
Just noticed that the Gnome extension "Ubuntu dock:" had been installed automatically during some system update. Removed it and tried again and now I do seen the windows most of the time. But intermittently the same things keeps happening: open a browser and it is not visible in the dock.

Moving it to a different workspace using Sfhit+Ctrl+Alt+Up/Down consistently makes it appear.

I hope this does not make things even more obscure...

**Comment by silviobierman** [comment]
The plot thickens!
The intermittent behavior of Chromium / Chrome windows being shown or not has reverted to consistent failure to show them, UNLESS they are moved to another workspace. That consistently makes the visible.

**Comment by balderclaassen** [comment]
Assuming you checked if the Ubuntu Dock has not been auto-installed again ?

**Comment by silviobierman** [comment]
Nope.

And I experimented some more. Disabled both DashToDock and WorkspacesToDock. Could not reproduce the problem. Re-enabled DashToDock. Still no problems. Re-enabled WorkspacesToDock. Bingo. The first Chromium window shows up, the second one opened in another workspace doesn't.

**Comment by silviobierman** [comment]
About the only thing non standard in my setup is workspaces set to fixed (6 of them) and set to primary display only.

**Comment by passingthru67** [comment]
I've got some ideas of what the problem might be, but, I can't be certain because I couldn't duplicate the issue on the computer I tested with. I'll have to install Gnome 3.26 on another computer and test again. Maybe I'll see something then.

**Comment by silviobierman** [comment]
Great! If there is any way I can help by testing stuff just let me know.

**Comment by silviobierman** [comment]
I got another glimpse at the horror that is Gnome shell without docked dash & workspaces so I am very motivated...

**Comment by passingthru67** [comment]
@silviobierman, Please download the 'fix-chrome-thumbnail' branch and test it on your unit. I'm taking a stab in the dark but hopefully it will work. Let me know how it turns out.

**Comment by silviobierman** [comment]
@passingthru67: I installed the branch and am sorry to say that the behavior has not changed.

**Comment by passingthru67** [comment]
@silviobierman: Would you test 'fix-chrome-thumbnail2' branch that I just uploaded.

**Comment by silviobierman** [comment]
You nailed it! Awesome!

I tried opening a dozen Chromium en Chrome windows. Not one went missing from the doch.

Thanks a lot for this fix. I am a Web-application developer working from a web-based dev. environment. Not seeing browser windows can be a pain that way :)

**Comment by passingthru67** [comment]
I did some more testing and found that this issue was also present in Gnome 3.24 on Wayland. I'll have to do more thorough testing on Wayland, especially since it's the future of the Gnome desktop.
