### ISSUE TITLE
Error after unlocking

### ISSUE THREAD

**Issue by texjoachim** [passingthru67/workspaces-to-dock#119]
###Linux Distribution version
openSUSE Tumbleweed

###Gnome Shell version
3.26

###Extension version or branch
latest

###Description of the problem
I get an DashToDock.dockManager._alllDocks[0] is undefined - error upon unlocking a locked Gnome desktop.
As a result I have to restart the Gnome shell.

###Steps to reproduce the problem
Turn on WorkspacesToDock, lock Gnome, unlock Gnome.

**Comment by passingthru67** [comment]
Do you have the latest dash-to-dock installed also? The reason I ask is because the error relates to the option of showing workspaces-to-dock when you hover over dash-to-dock. Also, are you on Xorg or Wayland?

**Comment by passingthru67** [comment]
I'm able to duplicate this issue on a 3.26 test unit. It looks like there's a delay in the creation of the Dash-to-Dock _allDocks[0] which wasn't there before. I'll make some changes to account for this.

**Comment by texjoachim** [comment]
Yes, I have the latest dash-to-dock, too.
I can't even remember if I ever turned on that option and I can't find a way to turn it off either now.

**Comment by passingthru67** [comment]
That option is at the bottom of the Behavior tab in the group of Misc Options.

**Comment by texjoachim** [comment]
Ah, found it. It was always turned off.

**Comment by micheleg** [comment]
> there's a delay in the creation of the Dash-to-Dock _allDocks[0]

is there?

**Comment by passingthru67** [comment]
@micheleg: The gnome-shell extension system notifies me that dash-to-dock is enabled, but, when I try to connect the signals _allDocks[0] is still null (not yet created). More like a system delay? What's weird is that it works fine if you restart gnome-shell or initially login to gnome. Anyway, I've added a wait idle loop so that the connection is made when _allDocks[0] becomes available. That seems to solve the issue.

**Comment by texjoachim** [comment]
Any ETA of when I can update?

**Comment by passingthru67** [comment]
I've had some setbacks. My 'fix' above didn't actually solve the issue. I'm digging deeper into the gnome extension system utils to see if I can determine what's actually going on.

**Comment by texjoachim** [comment]
Ah, I see.

**Comment by silviobierman** [comment]
I have the same problem (same error message) but it usually occurs directly after logon. 

This is on 3.26 on Wayland.

**Comment by passingthru67** [comment]
Todays' commit (https://github.com/passingthru67/workspaces-to-dock/commit/4b8cc3f661035791911166a26fcb97560ae1d74e) fixes the crash that occurs when dash-to-dock's _allDocks[0] is undefined. But, this is only part of the fix. The other part of the fix requires an update of dash-to-dock from their master repository (as of Oct 4)

Can somebody test this to make sure I haven't missed something?

**Comment by silviobierman** [comment]
I am running w2d master branch now. I could not find a recent master (or any other) branch of d2d so I am still on the current release for 3.26.

 So far so good. I will keep you posted.

**Comment by silviobierman** [comment]
Seems fine to me. No more crashes for a full day.

Thank you very much!

**Comment by passingthru67** [comment]
@silviobierman: Good to hear!

**Comment by pippo0312** [comment]
I confirm that using the w2d master branch on ubuntu 17.10 with wayland no problems are observed.
However using the default version installed with the browser I experienced several crashes

**Comment by passingthru67** [comment]
The new release is still under review at extensions.gnome.org (https://extensions.gnome.org/review/). They're pretty busy over there right now so give it a few more days.
