### ISSUE TITLE
GTK theming is broken (GNOME 3.26.1)

### ISSUE THREAD

**Issue by Hasbreak** [passingthru67/workspaces-to-dock#121]
###Linux Distribution version
Arch Linux 64 bit with multilib enabled

###Gnome Shell version
3.26.1

###Xorg or Wayland (or both)
The lastest Xorg-server package on Arch

###Extension version or branch
The newest version available on GNOME extensions store

###Description of the problem
As a result of the latest GNOME Shell update, sometimes workspaces frame isn't themed properly, and restarting Shell or killing Xorg session do not help.

_Edit: Shell theme is Adapta; applications theme is Adapta-Nokto._

###Steps to reproduce the problem
It got totally random to me. There's no distinguishable steps to reproduce it, yet almost everytime I boot into GNOME it's bugged.

![screenshot](https://user-images.githubusercontent.com/27376783/31311345-02f6915a-ab9a-11e7-90cd-e2edb39231ef.png)
_That is how it looks now_

**Comment by passingthru67** [comment]
What exactly to you mean the workspaces frame isn't themed? It would help if the screenshot was marked up showing the theming issue. Also, Is it just the Adapta theme that isn't working properly?

**Comment by Hasbreak** [comment]
![screenshot](https://user-images.githubusercontent.com/27376783/31312109-9adf3ffc-abaa-11e7-9dd9-7cd2bbae7572.png)
I should have included such a screenshot before, I admit that.
There were only two times I got it to be themed properly on GNOME 3.26.1 as on the screenshot above.

**Comment by passingthru67** [comment]
@Hasbreak: I just committed a fix for the theming issue. Please download the 'fix-theming' branch (https://github.com/passingthru67/workspaces-to-dock/archive/fix-theming.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder and restart Gnome Shell (alt+f2+r).

Let me know how it turns out.

**Comment by Hasbreak** [comment]
@passingthru67 I did the following, and it seems to fix the issue! :) To be sure, I've done some testing on my own to see whether the fix is permanent by restarting Shell _(alt+f2+r) + logging out_ and killing Xorg/GDM session. It looks like it is just fine as it was on GNOME 3.24.x.

**Comment by passingthru67** [comment]
The fix has been merged into the master branch.
