### ISSUE TITLE
GNOME-Shell 3.26 Warnings: Properties defined with 'let' or 'const'

### ISSUE THREAD

**Issue by saildata** [passingthru67/workspaces-to-dock#122]
Arch Linux | Gnome Shell 3.26 | Xorg | Extension version 43

### Description of the problem
Since GNOME-Shell updated to 3.26, I noticed some new warnings such as:  

```Some code accessed the property 'DockedWorkspaces' on the module 'dockedWorkspaces'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.```

It looks like Arc-Menu recently addressed these same issues by changing const/let to var in the appropriate places to avoid cluttering the log. [Arc-Menu PR#147](https://github.com/LinxGem33/Arc-Menu/commit/52fb83c565b15624950db536b3b66ac7d1d9ada8)

**Comment by passingthru67** [comment]
Yes, it has to do with the update of Gnome gjs to mozjs52. They're only warnings for now, but, they will need to be fixed eventually.

**Comment by passingthru67** [comment]
Fix merged into master branch.
