### ISSUE TITLE
Inconsitent margins of thumbnails

### ISSUE THREAD

**Issue by michaldaniel** [passingthru67/workspaces-to-dock#123]
###Linux Distribution version
Ubuntu 17.04 64bit

###Gnome Shell version
GNOME Shell 3.24.2

###Xorg or Wayland (or both)
Both. Screenshots taken on xorg session.

###Extension version or branch
42, acording to metadata.json

###Description of the problem
Inconsistent left and right margin of thumbnails in desktops preview. Spacing on the left is wider while the one on opposite site is more slim, especially visible when current workspace is surrounded by the highlight border.

Screenshots to demonstrate the issue:
![workspaces-to-dock-margin-issue](https://user-images.githubusercontent.com/1345297/31428656-d78fb5bc-ae6b-11e7-9e1b-a9e530575a8e.png)

This seems to be the case regardless of shell theme and dock position. When dock is positioned on the right, the left margin will still be wider and right spacing, then closer to the screen edge, narrower.

**Comment by passingthru67** [comment]
I'm no longer on Gnome 3.24.2 so I'll need to set up a test unit. Would you please export your settings by opening a terminal and typing "dconf dump /org/gnome/shell/extensions/workspaces-to-dock/". Then, copy/paste the results here. I'll need them to duplicate your environment.

A few questions:
1) What other extensions do you have enabled?
2) Does this margin issue show up when you have just a few workspaces, or is it constantly there no matter how many workspaces?

**Comment by michaldaniel** [comment]
Result of `dconf dump /org/gnome/shell/extensions/workspaces-to-dock/`

```primary-monitor=0
customize-thumbnail=false
workspace-caption-taskbar-icon-size=12.0
dashtodock-hover=true
workspace-caption-items=['windowapps:true']
dock-fixed=false
dock-edge-visible=false
hide-dash=false
customize-height=true
disable-scroll=false
overview-action='SHOW_FULL'
intellihide=false
thumbnail-size=0.11
workspace-caption-height=18.0
pressure-threshold=80.0
autohide=true
customize-height-option=1
quick-show-timeout=500.0
workspace-caption-menu-icon-size=18.0
dock-position='LEFT'
quick-show-on-workspace-change=true
background-opacity=0.69999999999999996
workspace-caption-windowcount-image=false
opaque-background=true
top-margin=0.050000000000000003
bottom-margin=0.050000000000000003
workspace-captions=false
```

1. What other extensions do you have enabled?

I disabled all other extensions and reloaded shell, the issue still presists.

2. Does this margin issue show up when you have just a few workspaces, or is it constantly there no matter how many workspaces?

Constantly there. But it's also present in your readme screenshots:
![obraz](https://user-images.githubusercontent.com/1345297/31437109-6fa0510a-ae84-11e7-9fd0-f7ebfd1004aa.png)

Here would be the case of big left vs small right margin. Right edge placement just makes it look a little less awkward.

Interestingly it doesn't show here:
![obraz](https://user-images.githubusercontent.com/1345297/31437166-aa64a1c4-ae84-11e7-9cdf-cb765b834a9e.png)

**Comment by passingthru67** [comment]
Some of the older screenshots in the readme file show this margin difference. But, it's been ages since I've seen it (I'm too lazy to update those screenshots). In fact, I just set up a test unit with Ubuntu Gnome 3.24 using Adwaita and it's looking just fine. I tested it with the Adapta shell theme also. Maybe I'm missing something? Do you have a multi-monitor setup?

**Comment by michaldaniel** [comment]
I edited out part about read me screenshots as I wasn't sure if it's not intentional in case or right aliment (matching top and outer margin?).

Anyway yes, its dual monitor setup with main on the left.

It's ancient more then 2 years old installation, if it's not known bug or something easy to reproduce there might be honestly many, many strange leftovers from multiple Ubuntu upgrades and years of usage. I'm not really sure what could influence such bug bug what I am saying is that this is far from sterile environment on fresh install.

When I'm back in front of that machine I might try to learn how to use UI inspector (I know there is one in GNOME, and that is about it) to figure out where this margin comes from. IDK how powerful it is but I'm going to check that.

**Comment by passingthru67** [comment]
Would you check if removing the second monitor makes a difference?

**Comment by 73** [comment]
Hi there, 
the shell theme is responsibe. I'm on Ubuntu 18.04 (gnome shell 3.28.1) and using Adwaita.
When I'm on the Arc-Theme, the difference is visible. When I deacitvate the user themes extension, the problem is gone.
I hope that helps.

Best
--73
