### ISSUE TITLE
[Feature Request] Middle click to close taskbar apps

### ISSUE THREAD

**Issue by lexman098** [passingthru67/workspaces-to-dock#125]
It would be nice to be able to close an application by just middle clicking its icon in the taskbar area.

PS: I love that you already made the feature to drag apps to different workspace. Keep up the good work!

**Comment by r3b311i0n** [comment]
+1

**Comment by diegosanz** [comment]
It will be great! +1

**Comment by passingthru67** [comment]
The lastest commits in the master branch add this feature.
