### ISSUE TITLE
[FEATURE REQUEST] Disable in fullscreen

### ISSUE THREAD

**Issue by GoodMirek** [passingthru67/workspaces-to-dock#126]
###Linux Distribution version
Fedora Core 27 (beta)

###Gnome Shell version
gnome-shell-3.26.1-2.fc27.x86_64

###Xorg or Wayland (or both)
Xorg (not tested under Wayland)

###Extension version or branch
The latest from E.G.O.
Where to get the version string from?
There is no version indication in settings of the plugin. Dash to Dock has About dialog, which shows the version string - would be great to have the same in Workspaces to Dock.

###Description of the problem
It is possible to disable Dash to Dock in full screen, what is useful e.g. for virtual machines, remote VNC and RDP connections.
Could we have the same option for Workspaces to Dock?

**Comment by vans163** [comment]
I think its better to have a show/hide hotkey, and remove the edge locking from the extension. This way if you fullscreen something and DONT want to see the workspaces, press your hotkey to hide it.

For example when I have multiple vms/VNC/RDP I prefer to see the extension overlayed ontop so I can quickly jump between them.

**Comment by passingthru67** [comment]
The latest commits add the option to enable/disable autohide in fullscreen. I also added a timeout when toggling the dock using a keyboard shortcut.
