### ISSUE TITLE
"Show Partial" overview mode dock doesn't remain expanded when dragging windows

### ISSUE THREAD

**Issue by PHLAK** [passingthru67/workspaces-to-dock#128]
### Linux Distribution version

Ubuntu 17.10

### Gnome Shell version

3.26.1

### Xorg or Wayland (or both)

Wayland

### Extension version or branch

v44

### Description of the problem

Workspace dock does not remain expanded when dragging a window in Gnome overview mode and "What should we do with the dock in overview mode?" is set to `Show Partial`.

Here's a video of the issue:

[![Workspaces to Dock Bug](https://img.youtube.com/vi/Cr1cXOGRt-k/maxresdefault.jpg)](https://youtu.be/Cr1cXOGRt-k)

### Steps to reproduce the problem

  1. Set "What should we do with the dock in overview mode?" to `Show Partial`
  2. Open one or more applications
  3. Activate Gnome overview mode by moving mouse to top left corner or pressing the super key
  4. Click and drag a window preview over to the workspace dock

**Comment by passingthru67** [comment]
Issue should be fixed in master and gnome-3.26 branches.
