### ISSUE TITLE
Feature request: middle click on icon to close

### ISSUE THREAD

**Issue by ddnexus** [passingthru67/workspaces-to-dock#129]
The single click on the icon of a window minimizes the window, but in order to close it you have to open the menu, search the name of the window in the list and click on the X icon. A simple middle click to close would be a lot faster!

**Comment by micheleg** [comment]
You are suggesting to middle-click on the windows preview, am I right?

**Comment by ddnexus** [comment]
Actually not on the window preview (the one of the dock desktop), because
the one you may want to close could be hidden by other windows, although it
could be a nice addition too. What I was suggesting is a middle click on
the little caption icon. You can select or drag a window by dragging that
icon, so why not using it also to close the window, without having to
right-click and click on the close x in a (possibly long) menu list?

**Comment by passingthru67** [comment]
The lastest commits in the master branch add this feature.
