### ISSUE TITLE
Gnome Shell become unusable on ubuntu 18.04

### ISSUE THREAD

**Issue by ddnexus** [passingthru67/workspaces-to-dock#134]
###Linux Distribution version
Ubuntu Bionic Beaver (development branch)
Release:	18.04

###Gnome Shell version
3.28.1

###Xorg or Wayland (or both)
both

###Extension version or branch
Latest on https://extensions.gnome.org/extension/427/workspaces-to-dock/

###Description of the problem
Makes the gnome shell totally unusable, i.e. the pointer is visible and can move around but no interaction could be done neither with the mouse nor the keyboard. No possibility to restart the shell, nothing. The only solution is restarting and removing the extension from the extensions dir in the x console before arriving to the desktop.

###Steps to reproduce the problem
Install the latest 18.04. The update of today broke it. (IIRC it installed some files for GDM and probably the gnome shell).

**Comment by sha-red** [comment]
This is not a workspaces-to-dock issue. Gnome shell (actually gjs, the Javascript engine) is broken since last summer, having huge memory leaks and killing wayland in the end. The only "solution" is to not use Gnome shell extensions.

**Comment by ddnexus** [comment]
> The only "solution" is to not use Gnome shell extensions.
which... said by a Gnome Extension author is huge :)

What I tried to report is that I never ever had any kind of problem with WTD, not even from last summer. Only from yesterday: the last update changed something that broke WTD badly. I just wanted to report it, because I liked WTD.

BTW, they fixed quite a bit of problems with extensions: some was randomly crashing the shell on wake-up, and now that is gone for good. Maybe WTD will work again with some future updates.

**Comment by ddnexus** [comment]
@sha-red: Oh... you are not the author!  My previous post didn't make any sense now that I know that!
Re-opening...

**Comment by sha-red** [comment]
Yes, sorry for the confusion. My comment was not meant as a prompt to close the issue.

**Comment by ddnexus** [comment]
@sha-red: itś not your fault: I just did't noticed it was not the author's answer. Thanks.

**Comment by silviobierman** [comment]
@sha-red: that is not entirely true. The Dash-to-dock extension (which I normally use alongside Workspaces-to-dock) broke down as well. But Dash-to-panel is working fine. I installed it as an alternative for Dash-to-dock is working fine under both X and Wayland.

**Comment by sha-red** [comment]
@silviobierman: Thanks for the hint, maybe I'll try. My (and my fellow Linux user's) experience is, that gjs (Gnome's Javascript engine) is leaking like hell, and this concerns all shell extensions, but very differently. dash-to-dock seems to leak like hell, after 1 to 2 hours the machine freezes/crashes. Until last summer I had about 15 very usefull shell extensions running, currently only 3 with very low overhead.

**Comment by silviobierman** [comment]
@sha-red: Well, my experience with this is quite short and fresh. So I can not say how it will behave after a day or so. I ran it for about ten minutes yesterday and have been running it for about two hours today.

**Comment by zoppagency** [comment]
Amazing Extension, However the last 18.04 update freeze the click trackpad, even a usb mouse click. is gnome 3.28.1 ?

**Comment by taimir** [comment]
+1, exact same setup and issue as @ddnexus describes. Other extensions window-manager related extensions (e.g. dash-to-panel, windownavigator, etc.) seem to work just fine.

**Comment by silviobierman** [comment]
At this moment Workspaces to dock is the only extension I work with that is still causing pain. Dash to dock is working fine now and I have tried suggestions made for alternative extensions for WtD and found them to all work properly. However, since they all do not do wat I want I have removed them all and will wait for a fix.
I find myself doing almost everything on one workspace now. Brings back memories of working with Windows. Those are not the happiest memories...

**Comment by ddnexus** [comment]
@silviobierman: my personal alternative way to cope with the missing WtD is using a few extensions patiently configured to work together seamlessly.

After adapting to some changes I have to admit that I am not missing WtD too much. I prefer the new way now.

I like to have a minimal invasive UI, but you could configure the extensions in a quite different way. Here is the screenshot of my setup:
![alternative](https://user-images.githubusercontent.com/100721/39173414-dacc4a54-47ce-11e8-8c85-3419eda5fc49.png)

The extensions I use:
- [TaskBar](https://extensions.gnome.org/extension/584/taskbar/): very versatile, you can have a lot of the functionalities of WtD maybe with a different look. I use the top panel (not the bottom panel), hiding the activities menu and the Dock from overview. Opened tasks on the left, workspaces indicator in the middle and Favorites on the right. It provides the Thumbnails too. I use the other extensions below for the rest.
- Frippery Move Clock
- Bottom Panel (you may avoid this one if you use the bottom panel option in TaskBar)
- Always Zoom Workspaces (so the rare times I need the Overview it will be available immediately)
- Hide Top Bar (nice addition to have a bit more space in fullscreen mode)
- The setup works well also with No Title Bar

HTH

**Comment by ddnexus** [comment]
Then you might want to check libinput gestures: I couldn't live without it.

**Comment by minimec** [comment]
Given the errors I get from 'journalctl -f' ( https://gist.github.com/minimec/fd0d9feb1596493c827023510965b7d0 ), I guess we can nail down the problem to the following patch set:

http://launchpadlibrarian.net/366171231/gnome-shell_3.28.1-0ubuntu1_source.changes

   * workspaceThumbnail-only-update-_porthole-if-the-overview-.patch:
     workspaceThumbnail-rebuild-thumbnails-if-workareas-size-c.patch:
     workspaceThumbnail-initialize-porthole-based-on-workArea.patch:
  
These patches are marked "Cherry-picks from upstream", which is probably the reason why ubuntu users are (for now) the only ones facing the problem.

I for my part decided to go the hard way: I apt-pinned the old package versions, as I hope that a fix may come within days or maybe a week or so.

If you never apt-pinned something, you can just create a file like 'sudo nano /etc/apt/preferences.d/gnome-shell' and copy/paste the following content in it:

Package: gnome-shell
Pin: version 3.28.0-0ubuntu5
Pin-Priority: 1000

Package: gnome-shell-common
Pin: version 3.28.0-0ubuntu5
Pin-Priority: 1000

You then have to fetch the old package versions and use 'dpkg -i' to downgrade gnome-shell.

https://launchpad.net/ubuntu/+source/gnome-shell/3.28.0-0ubuntu5/+build/14546410/+files/gnome-shell_3.28.0-0ubuntu5_amd64.deb
https://launchpad.net/ubuntu/+source/gnome-shell/3.28.0-0ubuntu5/+build/14546410/+files/gnome-shell-common_3.28.0-0ubuntu5_all.deb

Cheers

**Comment by passingthru67** [comment]
Just uploaded ubuntu-18.04 branch (https://github.com/passingthru67/workspaces-to-dock/tree/ubuntu-18.04). Please install WtD manually by downloading this branch and extracting the download into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r). 

Let me know how it turns out. If everything works, I'll merge the changes into the master branch.

**Comment by taimir** [comment]
Works for me :) Thanks!

**Comment by silviobierman** [comment]
Just installed the ubuntu-18.04 branch. Works like a charm. Thank you very much!

**Comment by minimec** [comment]
Big THX!

**Comment by passingthru67** [comment]
Glad it works and apologies for the delay. Day job responsibilities and home projects during the evenings/weekends have limited my coding time. Let me know if anyone is interested in helping with this extension. There's a lot of features that could be added but I just don't have time right now.

**Comment by zoppagency** [comment]
Amazing! now is working

**Comment by silviobierman** [comment]
No apologies needed of course! We users of this extension are very grateful that it exists and that you keep it up to date even with a development version of Ubuntu.
Unfortunately I am also very swamped and lack the time to take on anything new. Thanks again for all the good work.

**Comment by passingthru67** [comment]
I merged the ubuntu-18.04 branch into master and uploaded a new release to https://extensions.gnome.org (v45 for Gnome 3.28).

**Comment by hirschferkel** [comment]
O.K. it's still a bug in Gnome 3.28.2... updated to 3.28.3 and now it works.

**Comment by Halfwalker** [comment]
18.04.3 with gnome-shell 3.28.4-0ubuntu18.04.1 randomly locks up after entering password on screen-unlock screen.  Rest of the system is fine, just gnome has gone to la-la-land.

`sudo journalctl /usr/bin/gnome-shell -f -o cat`

returns tons of these :

`JS ERROR: Exception in callback for signal: hot-corners-changed: (null)`

This is on a Lenovo X1 Carbon laptop.  There are a bunch of extensions enabled that I'm going to disable now.  System-monitor had appeared to be the culprit - was locking up almost every time with that one enabled, went for a whole day no lockups with it disabled.  Not using any of the dock-to-panel type extensions.
