### ISSUE TITLE
Fix overview layout geography when using Ubuntu dock.

### ISSUE THREAD

**Issue by passingthru67** [passingthru67/workspaces-to-dock#135]
###Linux Distribution version

###Gnome Shell version

###Xorg or Wayland (or both)

###Extension version or branch

###Description of the problem
When WtD is used in conjunction with Ubuntu dock, windows overlap Ubuntu dock when in overview mode.

###Steps to reproduce the problem

**Comment by jessedubord** [comment]
I'm also experiencing this in Ubuntu 19.10 (xorg session).

**Comment by DiegoCPB** [comment]
This happens because the extension checks only for the dash to dock. To solve this, it probably suffices to pass check for the ubuntu dock UUID and treat it everywhere like it was a enabled dash to dock.
