### ISSUE TITLE
Default install via standard procedure in Ubuntu 18.04 installs non-working vesion

### ISSUE THREAD

**Issue by silviobierman** [passingthru67/workspaces-to-dock#136]
The problem with Gnome-shell 3.28.1 where solved in the ubuntu-18.04 branche but when you to install a new plugin via the standard method (checking to "ON" button on the Gnome extensions page for Workspaces to dock) a version without the fix is installed. Also, the checkbox with Gnome shell versions does not list version 3.28.

**Comment by passingthru67** [comment]
Version 45 for Gnome 3.28 is under review at extensions.gnome.org. You won't be able to install the latest WtD from that site until the review process is completed.

**Comment by silviobierman** [comment]
Ok. Thanks for the info. I did not know they did an additional review after the developer of an extension releases a new version.

**Comment by ajayjhajharia** [comment]
how we can install through GitHub for Ubuntu 18.04.i am new to Linux Thanks in advance

**Comment by passingthru67** [comment]
BTW, To install WtD manually, download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail.com extension folder that contains the extension code. Simply copy that folder to your extensions folder at /home/ME/.local/share/gnome-shell/extensions (replace ME with your actual username). Next, restart Gnome Shell (alt+f2+r) or logout and log back in (if using Wayland). If Workspaces-to-Dock doesn't show up, you may need to enable the extension using Gnome Tweak tool.
