### ISSUE TITLE
Screen Locked up when entering activities view

### ISSUE THREAD

**Issue by truongan** [passingthru67/workspaces-to-dock#138]
###Linux Distribution version
Archlinux - so no version. Linux 4.16.7-1
Nvidia GTX 750
Dual monitor

###Gnome Shell version
`$ gnome-shell --version
GNOME Shell 3.28.2`

###Xorg or Wayland (or both)
Xorg

###Extension version or branch
Github master branch: commit 3be75cac027d2f5314323baa0eeefb2ffcd91ad9 Date:   Fri May 4 15:49:07 2018 -0400

###Description of the problem
When entering activities view, the whole screen is locked up. Effect still show when I hovering on windows but click them won't exit the activities view. `Esc` key won't work, press `Super` key again won't work either.

The only thing that can be done is Alt + F2 and `r` to restart shell.

###Steps to reproduce the problem
Enter activities view by press `Super` key, move mouse to hot corner (top left), or click the `activities` on top bar

**Comment by passingthru67** [comment]
I'd like to see what your gnome shell log looks like at the moment things crashed. Would you run the following command from a terminal ..

journalctl --since "YYYY-MM-DD HH:MM:SS" /usr/bin/gnome-shell > journaldebug.txt

Replace YYYY-MM-DD HH:MM:SS with the date and time (in the appropriate format like 2018-05-10 12:30:00) right before the lock up. Then post the results (journaldebug.txt) or send it to me via email (passingthru67@gmail.com).

**Comment by truongan** [comment]
This is a snippet of log right after I activate activites view.
`Thg 5 10 18:35:08 archlinux gnome-shell[26031]: JS WARNING: [/home/truongan/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js 800]: reference to undefined property "undefined"
Thg 5 10 18:35:08 archlinux gnome-shell[26031]: JS ERROR: Exception in callback for signal: trigger: TypeError: DashToDock.dockManager._allDocks[idx] is undefined
                                                DockedWorkspaces<._overrideGnomeShellFunctions/WorkspacesView.WorkspacesDisplay.prototype._updateWorkspacesActualGeometry@/home/truongan/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:800:1
                                                _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:575:9
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                show@resource:///org/gnome/shell/ui/workspacesView.js:491:9
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                show@resource:///org/gnome/shell/ui/viewSelector.js:285:9
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                _animateVisible@resource:///org/gnome/shell/ui/overview.js:554:9
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                show@resource:///org/gnome/shell/ui/overview.js:540:9
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                toggle@resource:///org/gnome/shell/ui/overview.js:670:13
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                _toggleOverview@resource:///org/gnome/shell/ui/layout.js:1236:13
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                                                _trigger@resource:///org/gnome/shell/ui/layout.js:1369:9
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                _onBarrierHit@resource:///org/gnome/shell/ui/layout.js:1411:13
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Thg 5 10 18:35:08 archlinux gnome-shell[26031]: JS ERROR: TypeError: area is null
                                                padArea@resource:///org/gnome/shell/ui/workspace.js:1048:9
                                                _updateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1294:20
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                _realRecalculateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1271:9
                                                wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                _recalculateWindowPositions/this._positionWindowsId<@resource:///org/gnome/shell/ui/workspace.js:1246:13
Thg 5 10 18:35:08 archlinux gnome-shell[26031]: clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
`
Right after that I do a Alt + F2 restart thing.

**Comment by passingthru67** [comment]
I see you have Dash to Dock installed. Would you disable the WtD option to 'show the dock when hovering over dash to dock extension'? It's in the Additional Hide/Show Options section under the Behavior tab.

**Comment by passingthru67** [comment]
BTW, what other extensions do you have installed and enabled?

**Comment by passingthru67** [comment]
Another question .. Do you use Dash-to-Dock with the multi-monitor option turned on? If so, would you turn it off and test again?

**Comment by passingthru67** [comment]
I've attached a secondary monitor to duplicate your setup. I now get the lockup when I have Gnome Shell's primary display set to the second monitor and DtD set to multi-monitor.

**Comment by truongan** [comment]
Glad you were able to reproduce it. 
I did try your aforementioned settings to some weird combo:
Disable "show dock on mouse hovering" allow me to exit the activites overview,  but the arrangements of window in activities view is all messed up and select a window does not have anny affect.
Disable "show on all monitor" in DtD does seem to be a work around.

**Comment by passingthru67** [comment]
I just pushed a commit that I believe will fix the issue. Would you download the latest master branch code and test it?

**Comment by truongan** [comment]
That was prompt bug hunting :D 
I can confirm that little change in the code does seem like a nice fix

**Comment by passingthru67** [comment]
Good to hear!
BTW, thanks for the help. Your feedback was important to the process.

**Comment by matclab** [comment]
I confirm the fix on my side too. Thanks a lot !
