### ISSUE TITLE
No mouse click is allowed

### ISSUE THREAD

**Issue by gideonso** [passingthru67/workspaces-to-dock#141]
###Linux Distribution version

Fedora 28

###Gnome Shell version

3.28.1

###Xorg or Wayland (or both)

Xorg

###Extension version or branch
 
44

###Description of the problem

disable mouse click. Cannot do any click action.

###Steps to reproduce the problem

Enable the extension and login to gnome-shell. No mouse click is allowed.

**Comment by passingthru67** [comment]
There have been recent changes in gnome shell related to the thumbnails that breaks WtD functionality. Have you tried the latest code from the Github master branch?

To install WtD manually, download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail.com extension folder that contains the extension code. Simply copy that folder to your extensions folder at /home/ME/.local/share/gnome-shell/extensions (replace ME with your actual username). Next, restart Gnome Shell (alt+f2+r) or logout and log back in (if using Wayland). If Workspaces-to-Dock doesn't show up, you may need to enable the extension using Gnome Tweak tool.

**Comment by gideonso** [comment]
The new version works fine. Thanks for taking care of this.
