### ISSUE TITLE
Extension breaks Gnome Shell on recent Fedora and OpenSUSE updates.

### ISSUE THREAD

**Issue by kitsuneflame** [passingthru67/workspaces-to-dock#142]
### Linux Distribution version
Fedora & OpenSUSE.

### Gnome Shell version
3.28.2.

### Xorg or Wayland (or both)
Both.

### Extension version or branch
Version 45.

### Description of the problem
Since latest update to Fedora (and OpenSUSE), when plug-in loads at start-up Gnome Shell appears to be active and functional but is not able to accept input.  The clocks ticks up, mouse moves, lock screen works, but you cannot interact with the Shell or pull up the activities menu.

The only solution is to remove the extension by going into a TTY and deleting it, then starting Gnome.

### Steps to reproduce the problem
Install on Fedora 28 with most recent updates (as of 17 May 2018) and then restart.  Once Gnome loads up, the system will not respond to input and you will have to pull up a TTY to remove the extension to regain a functional desktop.

**Comment by passingthru67** [comment]
I looked through the git gnome shell commits but I don't see anything that would break the extension. I may have to install Fedora to check out this issue.

In the mean time, try resetting WtD preferences by typing the following in a terminal.

dconf reset -f /org/gnome/shell/extensions/workspaces-to-dock/

Then enable WtD again and see what happens.

**Comment by tbutcaru** [comment]
Just update my Manjaro with latest gnome (3.28.2) and I have the same exact issue.
I had to login with a guest account, su to my user, remove the extension so that I can get back access to my desktop.

Haven't tried the `dconf reset` yet.

**Comment by passingthru67** [comment]
You noted that you were running WtD v45. I'm assuming you downloaded it from Github and installed it manually. Is that correct?

Would you install the latest github master branch and test it?

**Comment by tbutcaru** [comment]
I have v44 in the `metadata.json` file. I have installed it via extensions.gnome.org. 
I still have the backup of the old version. 

I could go on extensions and install it again from there. 
If everything is ok, can I just get the only configuration from `org.gnome.shell.extensions.workspaces-to-dock.gschema.xml` and add it to the newly installed version?

**Comment by passingthru67** [comment]
There have been recent changes in gnome shell related to the thumbnails that breaks WtD functionality. I've submitted a new version to extensions.gnome.org (v45) but it may be a while before it passes the review process and is activated on the site. They are currently swamped reviewing lots of extensions.

To install WtD manually, download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail.com extension folder that contains the extension code. Simply copy that folder to your extensions folder at /home/ME/.local/share/gnome-shell/extensions (replace ME with your actual username). Next, restart Gnome Shell (alt+f2+r) or logout and log back in (if using Wayland). If Workspaces-to-Dock doesn't show up, you may need to enable the extension using Gnome Tweak tool.

**Comment by kitsuneflame** [comment]
Sorry, it may have been version 44.  I must have mistyped it.  It was the version available from the extensions site.  I'll have to give the GitHub version a try.

**Comment by kitsuneflame** [comment]
UPDATE:  The newest version of the extension as it is in GitHub appears to work and does not lock up Gnome Shell.

**Comment by passingthru67** [comment]
@kitsuneflame thanks for the verification.
@tbutcaru, were you able to install the latest version from github?

**Comment by tbutcaru** [comment]
@passingthru67 yes, it works now! Thank you :)

**Comment by twifty** [comment]
Just came to report this bug, but it's already been fixed? I was worried there for a moment that my most used and by far favorite extension was lost to me. Keep up the great work :beers:
