### ISSUE TITLE
Workspaces aren't removed once empty and switching to another workspace

### ISSUE THREAD

**Issue by PHLAK** [passingthru67/workspaces-to-dock#145]
### Linux Distribution version

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04 LTS
    Release:	18.04
    Codename:	bionic

### Gnome Shell version

3.28.1

### Xorg or Wayland (or both)

Xorg

### Extension version or branch

45

### Description of the problem

After removing all windows from a workspace and switching to another workspace the empty workspace remains. This seems to happen somewhat inconsistently. For example, it usually doesn't occur immediately after booting the computer and logging in but  happens after a short period of time (~15 minutes) or after something specific happens (but I don't know what that something is). The only way to "fix" it is to log out and back in but will inevitably occur again after a period of time.

Example video of the problem: https://youtu.be/vRM-r8SDsbw

### Steps to reproduce the problem

  - Log into Gnome with the workspace-to-dock extension enabled
  - Wait a while (???)
  - Create a new workspace by dragging one or more windows in between two existing workspaces
  - Move those windows to another workspace
  - Switch to another workspace

**Comment by passingthru67** [comment]
@PHLAK Sorry I missed this issue. Is this still an issue? There was a v46 release for gnome 3.28 since then.

**Comment by PHLAK** [comment]
This issue solved itself a while ago. Not sure what actually solved it but thanks.

**Comment by twifty** [comment]
This issue still exists with the master branch. I'm on shell 3.32.2 running on Manjaro.

**Comment by fedor-elizarov** [comment]
Hello @passingthru67 ^.^

UP: Same problem on debian. Maybe reopen?

```sh
dron@gnu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
dron@gnu:~$ 
```

```sh
dron@gnu:~$ gnome-shell --version
GNOME Shell 3.36.3
dron@gnu:~$ 
```

`Xorg session`

```sh
dron@gnu:~/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com$ cat metadata.json 
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Transform Gnome Shell's overview workspaces into an intelligent dock.",
  "gettext-domain": "workspacestodock",
  "name": "Workspaces to Dock",
  "original-author": "passingthru67@gmail.com",
  "shell-version": [
    "3.36"
  ],
  "url": "https://github.com/passingthru67/workspaces-to-dock",
  "uuid": "workspaces-to-dock@passingthru67.gmail.com",
  "version": 53
}dron@gnu:~/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com$ 

```

other extensions if need info
```sh
dron@gnu:~/.local/share/gnome-shell/extensions$ ls
activities-config@nls1729                                    horizontal-workspaces@gnome-shell-extensions.gcampax.github.com
applications-overview-tooltip@RaphaelRochet                  netspeed@hedayaty.gmail.com
apps-menu@gnome-shell-extensions.gcampax.github.com          openweather-extension@jenslody.de
com.github@mehdioukik.theme_switcher                         places-menu@gnome-shell-extensions.gcampax.github.com
ding@rastersoft.com                                          status-area-horizontal-spacing@mathematical.coffee.gmail.com
extensions@abteil.org                                        todo.txt@bart.libert.gmail.com
gamemode@christian.kellner.me                                user-theme@gnome-shell-extensions.gcampax.github.com
gnome-shell-screenshot@ttll.de                               workspaces-to-dock@passingthru67.gmail.com
hide-activities-button@gnome-shell-extensions.bookmarkd.xyz
dron@gnu:~/.local/share/gnome-shell/extensions$ 
```

empty workspaces only disappear if I restart the shell
