### ISSUE TITLE
No keyboard or mouse input in gnome-shell after installing workspaces-to-dock

### ISSUE THREAD

**Issue by mcoyle1960** [passingthru67/workspaces-to-dock#151]
###Linux Distribution version
Ubuntu 18.04.1 LTS 
Kernel 4.15.0-34-generic

###Gnome Shell version
3.28.3

###Xorg or Wayland (or both)
X.Org X Server 1.19.6

###Extension version or branch
Main branch downloaded Sept 11, 2018

###Description of the problem
Once installed, mouse clicks are not recognized. Keyboard input is also lost in gnome shell (if another app is selected, Firefox for example, keyboard input is recognized).
There were no errors in .xsession
Doing a dconf reset -f ... did not fix the problem.

###Steps to reproduce the problem
I created a new user and installed only workspaces-to-dock. The problem was still there. If you need anything else, please let me know. Thanks for all your hard work.

**Comment by passingthru67** [comment]
@mcoyle1960 The main branch has been bumped to Gnome 3.30 compatibility. Please download and install the Gnome-3.28 branch and let me know how it turns out.

**Comment by passingthru67** [comment]
@mcoyle1960 Were you able to install the Gnome 3.28 branch and did the issue persist?

**Comment by passingthru67** [comment]
@mcoyle1960 I'm closing this issue. We can re-open if there is still a problem.
