### ISSUE TITLE
When Dash to Dock is installed as well screen lock fails.

### ISSUE THREAD

**Issue by horga83** [passingthru67/workspaces-to-dock#152]
###Linux Distribution version
Arch Linux latest updates

###Gnome Shell version
3.30

###Xorg or Wayland (or both)
Xorg

###Extension version or branch
Latest from git

###Description of the problem
When I have Workspace to dock installed as well as Dash to Dock the screen lock fails when initiated.  Basically the backgrounds disappear, Dash to Dock disappears, workspaces to Dock stays on the screen and there is no way to recover except Control-Alt-Backspace.

###Steps to reproduce the problem
Just install both extensions.

**Comment by passingthru67** [comment]
@horga83 I'll look into this as soon as I can.

**Comment by passingthru67** [comment]
@horga83 The latest commit in the git master branch should fix the issue. Please install WtD from the master branch and let me know how it works out.

**Comment by passingthru67** [comment]
@horga83 I'm closing this issue. We can re-open if there is still a problem.
