### ISSUE TITLE
No keyboard or mouse input in gnome-shell after installing workspaces-to-dock (on 3.30)

### ISSUE THREAD

**Issue by isac322** [passingthru67/workspaces-to-dock#154]
###Linux Distribution version

archlinux (most updated version)

```bash
> uname -a
Linux bhyoo-laptop 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux
```

###Gnome Shell version

```bash
> gnome-shell --version
GNOME Shell 3.30.0
```

###Xorg or Wayland (or both)

```bash
> sudo X -version
X.Org X Server 1.20.1
X Protocol Version 11, Revision 0
...
```

###Extension version or branch

master (3.30)

###Description of the problem

If I enable "workspaces-to-dock" and reload the desktop using 'r', mouse clicks or keyboard input will not work.

###Steps to reproduce the problem

Install workspaces-to-dock via AUR or manual git clone (I tried both of them) and enable it.

###Error log

	 9월 21 20:32:50 bhyoo-laptop gnome-shell[843]: JS ERROR: TypeError: this.actor is undefined
		                                             _updateSize@/home/bhyoo/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:2288:9
		                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
		                                             _resetPosition@/home/bhyoo/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:2415:9
		                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
		                                             _refreshThumbnails@/home/bhyoo/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:2442:9
		                                             wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
		                                             _overrideGnomeShellFunctions/Layout.LayoutManager.prototype._updateRegions@/home/bhyoo/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:713:17
	 9월 21 20:32:50 bhyoo-laptop gnome-shell[843]: JS WARNING: [/home/bhyoo/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js 2288]: reference to undefined property "actor"
	 9월 21 20:32:50 bhyoo-laptop gnome-shell[843]: JS WARNING: [/home/bhyoo/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/myWorkspaceThumbnail.js 868]: reference to undefined property "_switchWorkspaceNotifyId"
	 9월 21 20:32:47 bhyoo-laptop gnome-shell[843]: Extension "workspaces-to-dock@passingthru67.gmail.com" had error: TypeError: Meta.ScreenCorner is undefined
	 9월 21 20:32:46 bhyoo-laptop gnome-shell[843]: JS WARNING: [/home/bhyoo/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/myWorkspaceSwitcherPopup.js 173]: reference to undefined property "ScreenCorner"

**Comment by passingthru67** [comment]
@isac322 I haven't tested on Arch yet (only Ubuntu 18.10). I'll look into this as soon as I can.

**Comment by isac322** [comment]
@passingthru67 Thanks a lot!

**Comment by passingthru67** [comment]
@isac322 I just updated my Arch unit to Gnome 3.30 but I don't see any issues. I'll need some more information to duplicate your setup.

1) What other extensions do you have installed?
2) Would you send me a dump of your WtD configuration? Just type the following in the command line ..

dconf dump /org/gnome/shell/extensions/workspaces-to-dock/ > dconfdump.txt

Then post it here or email it to me at passingthru67@gmail.com.

**Comment by isac322** [comment]
@passingthru67 I sent two of them to email.
But weird thing is... when I turn off all of my extensions and only enabled `workspaces-to-docks`, same error are occurred.

**Comment by passingthru67** [comment]
Just committed the code fix to prevent the lockup. But, there's still an issue that relates to Gnome 3.30 mutter that prevents switching workspaces left/right using the mouse scroll or shortcut keys. See https://gitlab.gnome.org/GNOME/mutter/issues/270 for details.

**Comment by isac322** [comment]
@passingthru67 Thanks for the bug fix. It works when reset dconf related with this extension. and like you said, there's the scroll issue too.
We have a scrolling issue, but I think I can close this issue because you solved the problem mentioned in the title, but I'm not sure, so I'll leave it to you.
Thank you again for maintaining workspaces-to-dock!

**Comment by passingthru67** [comment]
@isac322 The scrolling issue is an upstream Gnome mutter bug (?). Hopefully things will work when that issue is resolved. I will go ahead and close this issue related to no keyboard and mouse.
