### ISSUE TITLE
Don't work on Ubuntu 18.10

### ISSUE THREAD

**Issue by PrzemekSkw** [passingthru67/workspaces-to-dock#157]
###Linux Distribution version
Ubuntu 18.10, Kernel = 4.18.0-10-generic

###Gnome Shell version
GNOME Shell 3.30.1

###Xorg or Wayland (or both)
x11

###Extension version or branch
Last

###Description of the problem
Fresh Ubuntu installation.Extensions don't work. When I click to triangle, Apps Center launch.
![zrzut ekranu z 2018-10-26 08-29-08](https://user-images.githubusercontent.com/25219988/47548530-a9addc00-d8f9-11e8-8a6f-f2b3154304b5.png)

###Steps to reproduce the problem

Reinstall extension doesn't help.

**Comment by PrzemekSkw** [comment]
It works on Wayland session.

**Comment by passingthru67** [comment]
@PrzemekSkw I'll check this out as soon as I can.
