### ISSUE TITLE
Shell crash when removing icon from Favorites.

### ISSUE THREAD

**Issue by mcoyle1960** [passingthru67/workspaces-to-dock#159]
###Linux Distribution version
Ubuntu 18.10 x86_64 

###Gnome Shell version
GNOME 3.30.2

###Xorg or Wayland (or both)
x11

###Extension version or branch
Fresh download from git on Feb 2nd

###Description of the problem
I am showing Favorites and "Show Partial". No other extensions running.
When I remove an icon from Favorites, gnome-shell freezes for 30 seconds, then relaunches. The icon is gone from the dock.

Did a dconf reset and fresh install. Problem persists. 

Dock is vertical on the right edge. 

###Steps to reproduce the problem
Mentioned above.

**Comment by passingthru67** [comment]
Issue confirmed. I'll look into it when I get a chance.

**Comment by passingthru67** [comment]
The latest updates in the Gnome 3.30 branch fix the issue. Please download and test.

**Comment by mcoyle1960** [comment]
Fixed. Thank you.
