### ISSUE TITLE
Favorite Shortcuts Panel, rearrange icons not possible.

### ISSUE THREAD

**Issue by tnilzon** [passingthru67/workspaces-to-dock#165]
Favorite Shortcuts Panel, rearrange icons by drag and drop is not possible. Should be working as in the Dash. Must be a bug.

**Comment by passingthru67** [comment]
I'll need more info to do any troubleshooting:

Linux distribution, Gnome-Shell version, Extension version, Xorg/Wayland?, a description of what actually happens and how to duplicate it? Any journal logs during the drag/drop attempt?

**Comment by tnilzon** [comment]
This issue is no longer valid. There was something wrong with my install. A re-install , and drag and drop works.
