### ISSUE TITLE
Workspaces do not appear on the screen

### ISSUE THREAD

**Issue by nlpsuge** [passingthru67/workspaces-to-dock#167]
###Linux Distribution version
Fedora 29

###Gnome Shell version
Gnome 3.30.2

###Xorg or Wayland (or both)
Xorg, please see:
$ ps -ef|grep Xorg
gdm       1909  1899  0 09:15 tty1     00:00:00 /usr/libexec/Xorg vt1 -displayfd 3 -auth /run/user/42/gdm/Xauthority -background none -noreset -keeptty -verbose 3
username  2432  2427  3 09:16 tty2     00:00:13 /usr/libexec/Xorg vt2 -displayfd 3 -auth /run/user/1001/gdm/Xauthority -background none -noreset -keeptty -verbose 3
username  6187  6147  0 09:22 pts/5    00:00:00 grep --color=auto Xorg
$ ps -ef|grep Wayland
username  6216  6147  0 09:22 pts/5    00:00:00 grep --color=auto Wayland

###Extension version or branch
I have no idea, But I have made this extension up-to-update from https://extensions.gnome.org/extension/427/workspaces-to-dock/.

###Description of the problem
Workspaces do not appear on the screen

###Steps to reproduce the problem
1. Reboot or start to enter Gnome
2. Press Super button or move cursor to the edge cannot trigger workspaces to be appeared.
3. Disable then enable workspaces-to-dock in https://extensions.gnome.org/local/ can fix this issue.

**Comment by passingthru67** [comment]
The release version on the extensions.gnome.org site doesn't have the latest fixes. Please download the latest code in the Github gnome-3.30 branch and install manually. The link to the Github 3.30 branch is https://github.com/passingthru67/workspaces-to-dock/tree/gnome-3.30. Click the green 'clone or download' button and then click the download zip link. After downloading, extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r). If Workspaces-to-Dock doesn't show up, you may need to enable the extension using Gnome Tweak tool.

**Comment by nlpsuge** [comment]
Thank for your advice. 

It seems thant the lastest 3.30 branch fixs my issue. I'll close this issue.
