### ISSUE TITLE
Duplicated thumbnail on login

### ISSUE THREAD

**Issue by giovanigm** [passingthru67/workspaces-to-dock#168]
###Linux Distribution version
19.04

###Gnome Shell version
3.32

###Xorg or Wayland (or both)
1.20.4

###Extension version or branch
50

###Description of the problem
On login, it creates a duplicate thumbnail of the workspace. No errors on Looking Glass.

![simplescreenrecorder-2019-04-22_22 21 11](https://user-images.githubusercontent.com/15115032/56545606-78336780-654e-11e9-905c-7b55425d1e43.gif)

###Steps to reproduce the problem
- Install the extension
- Log out
- Log in

**Comment by dpriedel** [comment]
I have this same problem.

Running gnome-shell 3.32.1 on Manjaro with Xorg.

If I do a 'restart' the problem clears.

**Comment by passingthru67** [comment]
I was finally able to duplicate the issue on my laptop (desktop had no issues). I'll have the fix uploaded soon.

The fix is basicly to revert some code I removed in v50 for Gnome 3.32 (the layoutManager _updateRegion function). I didn't think the override was needed any more. I was wrong.

**Comment by passingthru67** [comment]
@giovanigm @dpriedel I just uploaded the fix to the master branch. Please download and test. Let me know how it turns out.

**Comment by dpriedel** [comment]
I just tried it and it seems to work.


Thanks !!!

**Comment by giovanigm** [comment]
I've tried and it worked for me too.

Thanks!
