### ISSUE TITLE
Hide the Gnome Shell Dash does not work

### ISSUE THREAD

**Issue by ddnexus** [passingthru67/workspaces-to-dock#170]
Ubuntu 19.04
GNOME Shell 3.32.0
Xorg
WtD Version: Latest in GNOME extensions

The Hide the Gnome Shell Dash does not work.
Select or unselect the option, the Dash is always shown.

**Comment by ddnexus** [comment]
Actually, I should have said that it does not hide the Dock...

**Comment by passingthru67** [comment]
@ddnexus Are you referring to the Ubuntu Dock? WtD does not hide the Ubuntu Dock nor Dash-To-Dock. It only hides Gnome-Shell's dash.

**Comment by ddnexus** [comment]
Sorry, I don't remember that after so long. I am using it fine now, so I am closing the issue. Thanks.
