### ISSUE TITLE
GNOME 3.34: Horizontal workspaces native support

### ISSUE THREAD

**Issue by alex285** [passingthru67/workspaces-to-dock#173]
Perhaps you will find these patches for 3.34 useful;
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/575

**Comment by passingthru67** [comment]
@alex285 Thanks for the information. I'll be looking into this.

**Comment by passingthru67** [comment]
@alex285 WtD master now incorporates the Gnome 3.34 native horizontal switching

**Comment by alex285** [comment]
many thanks! im getting back to it!!
actually i just uploaded a video on it! https://youtu.be/EedIKwPxRAA
