### ISSUE TITLE
Smaller customized width (either Feature Request or Bug)

### ISSUE THREAD

**Issue by akvadrako** [passingthru67/workspaces-to-dock#174]
###Linux Distribution version
Ubuntu 19.04

###Gnome Shell version
3.32.1

###Xorg or Wayland (or both)
Xorg (soon both)

###Extension version or branch
50

###Description of the problem
I would like to be able to customize the width of the dock (when on the side).

###Steps to reproduce the problem
I see there is a setting called "Customize the workspace thumbnail size", however it doesn't go below "10%" and it seems to have almost no effect. "10%" is almost the same as "25%" and it's much too wide. I would like it to be 100-200px or "5%".

**Comment by akvadrako** [comment]
Actually, I see that a workaround is to add many work-spaces. That's fine for me, but it took a while to figure out.

**Comment by yoselibero** [comment]
Yes please, the minimal width in this case is too big.

**Comment by passingthru67** [comment]
Pull request for a reduced minimal thumbnail size to 5% has been merged.
