### ISSUE TITLE
Dock doesn't show up

### ISSUE THREAD

**Issue by UserBlackBox** [passingthru67/workspaces-to-dock#182]
###Linux Distribution version
Ubuntu 18.04.03

###Gnome Shell version
GNOME 3.28.2

###Xorg or Wayland (or both)
Xorg

###Extension version or branch
Latest on gnome shell extension site

###Description of the problem
Dock doesn't work, requires restart to reload. Happens after suspend.

![Screenshot from 2019-11-22 11-10-08](https://user-images.githubusercontent.com/36890802/69441658-1a037880-0d19-11ea-95a0-dffec59cf1b8.png)

**Comment by hexadecimalDinosaur** [comment]
I am closing this because I stopped using GNOME as my desktop environment a while ago and it seems nobody else has had this issue
