### ISSUE TITLE
Super+W for "switching to upper desktop" stops working while extension is on

### ISSUE THREAD

**Issue by amireldor** [passingthru67/workspaces-to-dock#183]
###Linux Distribution version

Ubuntu 18.04 and Fedora 31

###Gnome Shell version

3.28.2

###Xorg or Wayland (or both)

Xorg, I think

###Extension version or branch

Whatever is in extensions.gnome.org

###Description of the problem

I have my "switch to upper desktop" shortcut key as Super+W. Sometimes while workspace-to-dock is enabled then this shortcut doesn't work. Disabling the plugin returns my shortcut.

While the extension is on, and the problem occurs, I can go to the shortcuts settings and default the "move to upper desktop" and set it again to Super+W and it works, but then after a short time it stops working and disabling the extension remedies the situation.

Worth noting that my "move to bottom desktop" is Super+S and it continues to work all the time.

###Steps to reproduce the problem

:man_shrugging: 

But seriously, I believe an "aha!" solution from one of the devs will surface up.

**Comment by passingthru67** [comment]
@amireldor Try turning off the 'Toggle the dock with a keyboard shortcut' option. It's found in the 'Additional Hiding & Showing Options' section under the Behavior tab. BTW, the keyboard shortcut to show/hide the dock is Super+W.

**Comment by amireldor** [comment]
That must be it!
