### ISSUE TITLE
3.36 release version blocks favourites

### ISSUE THREAD

**Issue by silviobierman** [passingthru67/workspaces-to-dock#194]
I work on Fedora 32 beta with Gnome 3.36.1 and had a master from about two weeks ago running fine. I just upgraded to the published version and now my dash no longer appears (both with dash-to-dock and without installed). My other laptop runs Ubuntu 20.04 and has the same issue.

**Comment by passingthru67** [comment]
@silviobierman I'm not sure I understand what you're describing. Are you saying that the favorites panel on Workspaces-to-Dock no longer appears or are you saying Dash-to-Dock no longer appears?

**Comment by silviobierman** [comment]
When I install Workspaces-to-dock the I can no longer access my favorites panel so I can not launch any application. This happens both with Dash-to-dock (which is my usual combo) as with the plain/default Gnome shell dash. Once I remove W2D things are back to normal.
This did not happen with a pre-release W2D version I took from about 4-6 weeks ago (I do not remember exactly when but I think it was a special 3.36 branch that I installed when I moved to Fedora32-dev) but when I noticed that the 3.36 version had been released I removed that version and upgraded. Since then I have this problem both on my Fedora32 and my Ubuntu20.04 machines.

Workspaces to dock itself is working fine btw. But without a dash/favourites the Gnome-shell is quite useless.

**Comment by passingthru67** [comment]
@silviobierman There's an option in WtD preferences that hides the Gnome Shell Dash. This option now also hides Dash-To-Dock since it's latest release. Try unchecking the 'hide-dash' option under WtD preferences.

BTW, accessing the preferences may be broken until Gnome 3.36.2. If that's the case, use dconf to change the setting at org/gnome/shell/extensions/workspaces-to-dock/hide-dash to false.

**Comment by silviobierman** [comment]
Thank you very much. That was indeed the problem. Is that a new option? I did nothing to my WtD preferences so I would suspect this is something new.
I had no problem accessing the preferences from my browser.
Closing the issue.

**Comment by passingthru67** [comment]
@silviobierman No, it's not a new option. The option targets the Gnome Shell dash but it now also hides Dash-to-Dock. I'm not sure if it's a change in Gnome Shell or Dash-to-Dock.
