### ISSUE TITLE
Show when moving workspaces

### ISSUE THREAD

**Issue by retrop7** [passingthru67/workspaces-to-dock#24]
I love this extension super usful. The one think I wish it had (I hope this is the right place for suggestions) is a show when switching wrokspaces option. Right now when I switch workspaces I get this very basic arrow with boxes (I think you know what I mean) I would like a bit more information with my workspace indicator and showing this dock would do just that. I often forget where I have put things and a quick glance at the dock is all I need to remember.

**Comment by passingthru67** [comment]
The feature has been added to the master branch.
