### ISSUE TITLE
Mouse wheel doesn't switch workspaces when running on Wayland

### ISSUE THREAD

**Issue by mildred** [passingthru67/workspaces-to-dock#30]
In comment to the [extension website](https://extensions.gnome.org/extension/427/workspaces-to-dock/) someone reported that the mouse wheel doesn't work on Gnome Wayland. I can confirm this report.

**Comment by passingthru67** [comment]
This may have to wait until I can get a wayland session running long enough to troubleshoot the problem. It keeps crashing on me.

**Comment by passingthru67** [comment]
Tested this in Gnome 3.18 under Wayland and the mouse wheel seems to work fine. Is it still an issue?
