### ISSUE TITLE
Outdated according to Gnome

### ISSUE THREAD

**Issue by j0hannes** [passingthru67/workspaces-to-dock#31]
just a hint

**Comment by passingthru67** [comment]
What version of Gnome are you running?

**Comment by j0hannes** [comment]
My distro (Arch) just upgraded to 3.16.

**Comment by passingthru67** [comment]
That's strange. I run Arch with Gnome 3.16 also and I had no problems upgrading the extension. Try restarting Gnome Shell (Alt+F2 and r) before upgrading from the extension site.

**Comment by j0hannes** [comment]
Finally, I was able to update it via gnome-tweak-tool.

**Comment by passingthru67** [comment]
Closing this issue. Nobody else has reported having this problem.
