### ISSUE TITLE
Remove rounded corners when maximized

### ISSUE THREAD

**Issue by LeOSW42** [passingthru67/workspaces-to-dock#32]
Hello,

As for the Dash to Dock extension, it can be great to remove rounded corners when we choose to extend to full height the dock.

Léo

**Comment by LeOSW42** [comment]
Looks like just need to remove `this._settings.get_boolean('dock-fixed') && ` on lines 859, 868 and 877 of the dockedWorkspace.js file

**Comment by passingthru67** [comment]
You're right. That's a bug introduced in the latest version (v28 for Gnome 3.16). It was working just fine in previous versions.
