### ISSUE TITLE
Maximized windows have a margin of 1px

### ISSUE THREAD

**Issue by m20554443** [passingthru67/workspaces-to-dock#35]
There is a small gap (of 1px?) between a maximized window and WtD, see screenshot. Is there a way to to reduce the margin of WtD (or the maximized window) to zero?

![gap](https://cloud.githubusercontent.com/assets/856059/8520410/119bc79c-23da-11e5-8549-0750b7d34ca7.png)

**Comment by passingthru67** [comment]
I believe the 1px margin is caused by the 1px border needed to trigger the dock when it is hidden. I may be able to remove that border if the dock is configured to always be visible. Are you using WtD in the 'fixed and always visible' configuration?

**Comment by m20554443** [comment]
Right, I am using it in the 'fixed and always visible' configuration (widescreen monitors provide far more horizontal space than I need).

**Comment by micheleg** [comment]
I had the same problem some times ago, I got rid of any triggering pixel in my extension, you might be interest in this and following commits: https://github.com/micheleg/dash-to-dock/commit/0c0e88d26b76d4f046aff81ca73c14089a2ab3da .

In any case you should be able to track struts from an internal actor without that 1px padding.

**Comment by passingthru67** [comment]
Thanks @micheleg. I'll take a look at that code.
