### ISSUE TITLE
Gnome 3.18

### ISSUE THREAD

**Issue by hhlp** [passingthru67/workspaces-to-dock#38]
Doesn't work in gnome 3.18 I installed from gnome-shell extension finish the instalation well but the botton convert to off again after refresh page with F5 and doesn't install it at all.

**Comment by passingthru67** [comment]
You'll need to install manually from Github. The latest version on the extension site is for Gnome 3.16. The Gnome 3.18 version is still under review.

**Comment by hhlp** [comment]
it's work now from GNOME Shell Extensions

thx, for your help
