### ISSUE TITLE
Dock position

### ISSUE THREAD

**Issue by eriolloan** [passingthru67/workspaces-to-dock#39]
Hi, first of thanks for the great extension.

I can't seem to find how to set the dock position (neither in the settings nor in dconf). I've tried setting it manually editing the .js files but I'm no coder and it got kind of messy after a bit.

As a feature request : could it be possible to have an easy way to set the orientation of the panel and get it to also affect the layout of the workspaces? There's this grid extension out there but it's not maintained anymore apparently and I know Frippery bottom panel forces your workspaces into a horizontal layout so it's not a GS limitation, but I'd rather use workspaces to dock (more to my taste and more options). IMHO it would be great to get this behaviour through your extension.

Thanks!

**Comment by passingthru67** [comment]
The dock position (left/right of screen) is only available for Gnome 3.16 and 3.18.

As for a horizontal layout, I plan on providing a top/bottom positioning option. But, a grid layout for the workspaces is not something I have thought much about. I don't have the time right now, but, I'll keep it in mind for the future if the demand is high.

**Comment by eriolloan** [comment]
That's weird... I'm using 3.16 yet! Where do I find the appropriate setting ?

The grid layout was not exactly my request (it's more about having the linear layout either vertical as it curently is or horizontal, depending on the dock orientation) although I guess there is some demand for it since the grid extension is currently broken.
Any ETA for the horizontal layout ?

**Comment by passingthru67** [comment]
Workspaces-to-Dock v.30 is the latest version for Gnome 3.16. Go to the extension preferences window and locate 'Show the dock at the following screen position' under the 'General' tab.

I can't really give you an ETA for the horizontal position option. I'm helping out with the development of another extension right now so it has delayed things with workspaces-to-dock. But, it is in the works.

**Comment by passingthru67** [comment]
Horizontal layout (top/bottom position) has been added to the master branch.
