### ISSUE TITLE
[idea] Detect the window list, and don't cover it when full height-fill-the-screen option is on.

### ISSUE THREAD

**Issue by trusktr** [passingthru67/workspaces-to-dock#41]
Just like with the top panel, it'd be nice if workspaces-to-dock detected the bottom window list panel and not cover it. For example, here's what it looks like when the dock covers the window list (which is an official extension provided by Gnome), look at the bottom left:

![screenshot from 2015-11-30 12-28-38](https://cloud.githubusercontent.com/assets/297678/11483574/e4c33780-975d-11e5-9a50-fd9c4f40e5ce.png)

I can work around the problem by finding the right percentage number for the bottom margin:

![screenshot from 2015-11-30 12-30-34](https://cloud.githubusercontent.com/assets/297678/11483614/2f570524-975e-11e5-9c86-c9de27b41f20.png)

**Comment by passingthru67** [comment]
It's hard to test compatibility with every extension. But, I agree, that it should work with Gnome's official extensions. I'll look into fixing this.

**Comment by passingthru67** [comment]
This issue should be fixed in the latest commits to the master branch.

**Comment by trusktr** [comment]
Sweet. Looking forward to test. By the way, how do I test a plugin that is not on extensions.gnome.org?

**Comment by passingthru67** [comment]
To install the WTD manually, download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (Alt+F2+r). You may need to enable the extension using Gnome Tweak tool.
