### ISSUE TITLE
Can't move window to the second screen if dock is between.

### ISSUE THREAD

**Issue by kubecz3k** [passingthru67/workspaces-to-dock#44]
When dock is between two screens and intelligent hiding is turned on then it's impossible to move window from the screen with the dock to the second one.

**Comment by passingthru67** [comment]
This issue is basicly the same as #23. See Issue #23 for a solution.

**Comment by kubecz3k** [comment]
Will close the issue since it's duplicate. 
ps.
Thanks a lot  for your work @passingthru67! Your extension is simply the best :)
