### ISSUE TITLE
Doesn't work in gnome-shell 3.18.3

### ISSUE THREAD

**Issue by ndias** [passingthru67/workspaces-to-dock#46]
I have Fedora 23 with gnome-shell 3.18.3, I installed from the extensions page and from github and doesn't work, I have an icon saying ERROR when I see the extensions in the browser, with gnome-tweak-took says "Error loading extension"

**Comment by passingthru67** [comment]
Try disabling all other extensions. You may be experiencing a conflict with another extension. If the behavior persists with other extensions disabled, check for extension errors by typing "journalctl -b | grep -i gnome-session" in a terminal and watch for JS error logs related to the extension.

**Comment by ndias** [comment]
Even with all extensions disabled I can't enable the extension.

 No errors in journal.

 In https://extensions.gnome.org/extension/427/workspaces-to-dock/ ther
e are another person with the same problem, if I delete the extension,
I can't install from the above link, it displays an error.

Nuno

On Tue, 2016-01-26 at 07:56 -0800, passingthru67 wrote:
> Try disabling all other extensions. You may be experiencing a
> conflict with another extension. If the behavior persists with other
> extensions disabled, check for extension errors by typing "journalctl
> -b | grep -i gnome-session" in a terminal and watch for JS error logs
> related to the extension.
> —
> Reply to this email directly or view it on GitHub.
-- 
Nuno Dias <Nuno.Dias@gmail.com>

**Comment by passingthru67** [comment]
Have you tried to restart Gnome Shell (Alt+F2+r) before reinstalling?

**Comment by ndias** [comment]
Yes, if I disable all extensions, remove the extension, restart gnome-
shell, go to the extensions page, I can install the extension again,
but doesn't work after, it ask if I want to install, I press yes, but
the button goes off in the extension page.

Nuno

On Tue, 2016-01-26 at 08:41 -0800, passingthru67 wrote:
> Have you tried to restart Gnome Shell (Alt+F2+r) before reinstalling?
> —
> Reply to this email directly or view it on GitHub.
-- 
Nuno Dias <Nuno.Dias@gmail.com>

**Comment by passingthru67** [comment]
I'll have to install Fedora 23 and check it out. There may be something specific to that distribution.

**Comment by passingthru67** [comment]
Okay, here's where I'm at .. 
I've got Fedora 23 with GS 3.18.3. I initially installed the extension with GS 3.18.1 and then I updated to GS 3.18.3. I then removed the extensions and tried to reinstall from https://extensions.gnome.org and it failed to reinstall. I have no explanation as to why it failed to reinstall. But, after I restarted Gnome Shell (alt+f2+r), I was able to reinstall.

**Comment by passingthru67** [comment]
You said you attempted to install WtD manually from Github. Could you give me more detail about your manual install process? I'd like to try and duplicate it.

**Comment by ndias** [comment]
Get the extension from github (zip format), then use gnome-tweak-tool
to load the extension, you can do this with the in the extensions tab
in gnome-tweak-tool, in the end of the page.

Nuno

On Thu, 2016-01-28 at 07:38 -0800, passingthru67 wrote:
> You said you attempted to install WtD manually from Github. Could you
> give me more detail about your manual install process? I'd like to
> try and duplicate it.
> —
> Reply to this email directly or view it on GitHub.
-- 
Nuno Dias <Nuno.Dias@gmail.com>

**Comment by passingthru67** [comment]
Try this instead ..
Download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r). If WtD doesn't show up, you may need to enable the extension using Gnome Tweak tool.

**Comment by passingthru67** [comment]
@ndias, Were you able to install WtD using the instructions above?

**Comment by ndias** [comment]
I replied but for some reason the mail not created an update here!!

Done everything as requested ... in gnome-tweat-took says "error loading extension"
the same in the browser."

**Comment by passingthru67** [comment]
Go to your extensions folder (~/.local/share/gnome-shell/extensions) and see if workspaces-to-dock@passingthru67.gmail.com folder is there.

**Comment by ndias** [comment]
Yes, it is there, I can access to the configuration of this extension also

**Comment by passingthru67** [comment]
If you've got some time, I'd like to run through some troubleshooting steps to isolate the issue. Also, if you would prefer, you can email me directly at passingthru67@gmail.com.

**Comment by passingthru67** [comment]
Issue fixed on master branch.
