### ISSUE TITLE
Can't grab scrollbar in tiled windows

### ISSUE THREAD

**Issue by zagortenay333** [passingthru67/workspaces-to-dock#48]
When I have a window tiled I can grab the scrollbar by moving the mouse to the edge but not while this extensions is enabled. Any way to fix it? It's pretty annoying.

**Comment by passingthru67** [comment]
There should only be 1px at the edge of the screen that allows the mouse to hover over the dock and scroll to change workspaces or to display the dock (assuming you don't have the 'Leave visible edge' option turned on). Are you saying that the 1px dock edge is interfering with accessing the window scrollbars? Any particular app windows or all apps? Does it only do it when the windows are tiled?

**Comment by zagortenay333** [comment]
All apps are affected. That 1px is interfering with the ability to fling your mouse into the edge and grabbing the slider. This is even the case when the ability to show the dock with mouse hover is turned off.

Maybe  at least in that case it could be removed?

**Comment by passingthru67** [comment]
There are other detection schemes that don't require a 1px edge but they complicate things. I could rework the code to remove the 1px edge if (1) autohide pressure option is turned on and (2) disable scrolling when hidden is turned on. I'll look into it.

**Comment by passingthru67** [comment]
Please download the window-scrollbar-fix branch zip at https://github.com/passingthru67/workspaces-to-dock/archive/window-scrollbar-fix.zip and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail.com folder. Copy it to your ~/.local/share/gnome-shell/extensions folder and restart Gnome Shell (alt+f2+r).

Let me know if this fixes the issue with the scrollbars.

**Comment by zagortenay333** [comment]
Yep works!

**Comment by zagortenay333** [comment]
Looks like this issue reappeared in gnome 3.24. Installed from the gnome-shell-extensions website.

**Comment by passingthru67** [comment]
I just tested and it's working for me. Any particular application giving trouble?

Try this ..  export your settings by opening a terminal and typing "dconf dump /org/gnome/shell/extensions/workspaces-to-dock/". Then, copy/paste the results here. I'll try to duplicate your environment. Maybe I'm missing something.

**Comment by zagortenay333** [comment]
All applications are affected again.

```[/]
customize-thumbnail=true
intellihide=false
dock-edge-visible=false
show-delay=0.050000000000000003
customize-height=true
animation-time=0.050000000000000003
thumbnail-size=0.10000000000000001
hide-delay=0.050000000000000003
autohide=true
workspace-captions=false
```

**Comment by passingthru67** [comment]
Looks like you need to activate the 'Disable scroll when dock is hidden to prevent workspace switching' option. It's found under the Miscellaneous options of the Behavior tab.

**Comment by zagortenay333** [comment]
Yeah, that's it.
