### ISSUE TITLE
scrolling inconsistency

### ISSUE THREAD

**Issue by gizzmoguy** [passingthru67/workspaces-to-dock#49]
If animations are off and i use workspaces to dock to get to all apps overview i may or may not be able to scroll through application list. When i turn animations back on again scrollling though all apps works again with issues am using gnome shell 3.18-2  lenovo t530 i7

**Comment by The-Panacea-Projects** [comment]
I have several questions.
1) Is the dock in fixed position mode or do you have autohide+intellihide turned on
2) What side of the monitor screen is the dock positioned
3) What are you using to turn off animations

**Comment by gizzmoguy** [comment]
Replying to The-Panacea-Projects

1)The dock is set to "Show on Hover" setting

2)The dock is placed on the left side of the monitor( but the issue occurs in any position)

3)Am using the "gnome tweak tool" to turn off animation.

hope the helps thanks.

**Comment by passingthru67** [comment]
This issue has been fixed with commit 692973aae92b8dabdc42c21e85798ef0b4d371a0

**Comment by gizzmoguy** [comment]
Thanks a lot you have made me a very happy gnome user. Keep up the good
work this is my favorite extension and you have made worlds better. saw it
demo on WOGUE Youtube channel.
