### ISSUE TITLE
Animation inconsistency 

### ISSUE THREAD

**Issue by gizzmoguy** [passingthru67/workspaces-to-dock#50]
Sorry but i found another inconsistency. When you click  icon in the favorite dash  to all application overview there is  no animation ( which in my opinion is awesome) but if click that same icon whilst  all application overview there is an animation where the i cons fly back to where the click happened. it would be nice if it would not animate all together hope that helps.

**Comment by passingthru67** [comment]
Figures that fixing one would break the other. Anyway, I'll push out a fix soon.

**Comment by passingthru67** [comment]
Commit 3e153de97c73472344ce6466d9819feaa64c1cf3 should fix the animation inconsistency.

Let me know if you find any more issues.

**Comment by gizzmoguy** [comment]
Alright man cool and thanks for you hard work truly appreciate what you do.

**Comment by gizzmoguy** [comment]
Ok commit 3e153de fixed the animation inconsistency but I
 unfortunately  found two other bugs. They don't bother me am
 telling you my finding as they were.

1) if you drag an application from the all apps overview unto the dock when
adding to favorites it crashes work spaces to dock.
2)if an application is drag from the favorites bar to a different workspace
the application will not open where you drag it except it
 will open on the current or focus workspace instead of where you had
dragged it to.
