### ISSUE TITLE
Dragging application bugs

### ISSUE THREAD

**Issue by gizzmoguy** [passingthru67/workspaces-to-dock#51]
Ok commit 3e153de fixed the animation inconsistency but i unfortunately  found two other bugs

1) if you drag an application from the all apps overview unto the dock when adding to favorites it crashes work spaces to dock.
2)if an application is drag from the favorites bar to a different workspace the application will not open where you drag it except it
 will open on the current or focus workspace instead of where you had dragged it to.

**Comment by passingthru67** [comment]
I'm not able to duplicate the issue. I need more details to set my workstation up like yours.
1) Are you using dynamic or static workspaces?
2) Do you use icons on the Desktop?
3) Which application are you dragging and dropping? I remember some apps like Firefox were known to give issues when dragging to another workspaces, even in the normal Gnome Shell workspace slider.

**Comment by gizzmoguy** [comment]
1)   Yes am using dynamic workspaces.
2)  No i do not an active desktop


3)  After more testing i realize that the behavior was not consistent
between apps. Meaning some would work as expected and some would not at
this point i don't really want to call this a bug
Some application would steal focus example gnome music( drag gnome music to
an empty desktop and it become the desktop in focus). Others like
popcorntime would not open on the desktop you dragged it to but would open
on the desktop in focus. So at this point i do not think it is a bug.

**Comment by gizzmoguy** [comment]
Just rearranging icon on in favorites on workspaces to dock causes it to
crash.

**Comment by passingthru67** [comment]
As for the applications not opening in the proper workspaces, this is an issue with Gnome Shell itself. Disable WtD and test the same apps using the overview worspace switcher/slider and I believe you'll find the same inconsistent behavior.

**Comment by passingthru67** [comment]
Would you send me a log output when you rearrange favorites that causes the crash? Just type "journalctl -f" in a terminal and, after the crash, copy/paste the output to a text file. Send it as an attachment to my email address at passingthru67@gmail.com

**Comment by passingthru67** [comment]
@gizzmoguy, The latest commits should fix the DND crashing issue.

Were you able to determine if the issue with applications opening on wrong workspaces was an upstream bug? The apps I've tested behave the same in Gnome Shell's workspace switcher and in WtD. Some open in the proper workspaces while others open only in the current workspace.

**Comment by gizzmoguy** [comment]
Yea i have gotten same result with you when i perform the same test. Apps
behave the same on WTD as well as gnome shell dash.

**Comment by gizzmoguy** [comment]
Latest commits definitely fix crashing issue.🙂 have not been able to
replicate any more issues.

**Comment by passingthru67** [comment]
I'll go ahead and close this issue then.

**Comment by gizzmoguy** [comment]
Hey dude how can i get workspaces to dock for gnome 3.20 i want to be a
tester

**Comment by passingthru67** [comment]
I plan on updating the master branch to Gnome 3.20 this week. In the mean time, try changing the metadata.json shell-version from 3.18 to 3.20. That should work.
