### ISSUE TITLE
Showing workspaces on mouseover of dock in favorites shortcut panel mode

### ISSUE THREAD

**Issue by capstan1** [passingthru67/workspaces-to-dock#53]
Hi!

I really like the extension and the idea of having the dock and the workspaces side by side (option "favorite shortcut panel") is just great, because the way of the mouse to drag&drop an app to a workspace is so much shorter!

But I usually have my dock visible all the time, which means that with this option the space used all the time is huge! 
I would love an option of fading in the workspaces right next to the dock when I hover the dock (there's an option of showing it on mouseover but in this way the workspaces are opposite or on top of the dock....) .

I hope you get, what I tried to explain ;)

Best regards
Eric

**Comment by passingthru67** [comment]
Let me see if I get this .. You would like ONLY the shortcuts (i.e. favorites) panel to show when the intellihide (i.e. dodge windows) option is enabled, unless you hover over the dock. Then, upon hovering, the shortcuts panel + workspaces thumbnails show.

Is this correct?

**Comment by capstan1** [comment]
Thanks for your fast reply!
![a](https://cloud.githubusercontent.com/assets/17147867/12930929/698d8ca4-cf7b-11e5-80e1-5220df4d03cf.png)


Nearly:
I want the favorites being shown always (like an dock/plank/unity dock) and then yes on hover allways the workspaces show.

I created an picture illustrating it (obviously without icons changing size :P )

**Comment by passingthru67** [comment]
Nice feature indeed. I need to think through how to code it, and also how it would affect the dynamic operation of the non-fixed dock.

**Comment by passingthru67** [comment]
@capstan1, I’ve added a new feature in the master branch that I think will work for you. It’s not exactly how you described above, but it was the best solution given the many ways the dock is used.

Here’s how to implement something similar to what you described above.
1) General Tab - position dock on the left of the screen and extend height of the dock to fill the screen.
2) Behavior Tab - Turn off fixed-dock mode and make sure both autohide and intellihide are turned on. Then set ‘what should we do with the dock when not dodging windows’ to ‘Show Partial Fixed’.
3) Favorites Tab - enable show a favorite shortcuts panel and set the shortcuts panel orientation in reference to the thumbnails to ‘INSIDE’

What you should see is a favorites dock fixed (always visible) on the left side of the screen. 
If you need to see the workspace thumbnails, just press the mouse pointer against the edge of the screen (assuming you have require-pressure enabled) and the dock will slide in completely to show the full dock.

Anyway, let me know how it works for you.

**Comment by PowerOfM** [comment]
I just wanted to say thank you so much, this works great for me!

**Comment by passingthru67** [comment]
Thanks. BTW, if anyone else is interested, there's a screencast of it in action at ..
https://www.youtube.com/watch?v=PpyLdt-Rfc4

**Comment by capstan1** [comment]
Hi passingthru,

I'm so so sorry! Because of really bad performance I had to switch from Gnome Shell. But know I'am back!
And I have to say: what you did is amazing! What you show in your video is exactly what I was looking for! Thank you!

Just one thing: I can't find the option "Show partial fixed" under preferences. Im on Ubuntu Gnome 16.04. Where can I enable this great feature?

Thank you again and again : I'm very sorry for requesting this and don't responding for so long!

**Comment by passingthru67** [comment]
I believe that particular feature is only on Gnome 3.18+. But, I should be able to backport it without any major issues. It will require some time though.

On the other hand, are you able to upgrade to Gnome 3.18+ using a PPA?

**Comment by capstan1** [comment]
Hi!
I'm on GNOME Shell 3.18.5 already. Also noticed that all the text  ‘what should we do with the dock when not dodging windows’  is missing under behaviour, not just the option "Show partial fixed"

![bildschirmfoto vom 2016-10-08 19-28-41](https://cloud.githubusercontent.com/assets/17147867/19214843/7a411a68-8d8d-11e6-9596-874fe81b86a0.png)

**Comment by passingthru67** [comment]
I edited my comments above to reflect my mistake. It's actually Gnome 3.20 when this feature was introduced.

**Comment by capstan1** [comment]
Tried to upgrade via ppa. Got various error texts, no animations and broken window decoration. So I had to go back.

If it's not too much work, I would be happy to get it in 3.18! If it's too much of a hassle (and I can understand it, as 3.18 already is quiet old) I'll wait for this feature for when I upgrade to Ubuntu 16.10 someday. :)

Thank you!
