### ISSUE TITLE
Dock animation freeze

### ISSUE THREAD

**Issue by CubeX00** [passingthru67/workspaces-to-dock#54]
Don't know if it fixed in newer versions, but in 27 if desktop is switched faster than popup animation finishes playing (i.e. with a mouse wheel), dock freezes util next mouse hover...

I've already made a submission through extensions.gnome.org but gona leave it here as well in case the bug is still present in newer versions.

**Comment by passingthru67** [comment]
Further testing revealed the issue in the master branch also. The latest master commits should fix this issue. Gnome 3.14 and 3.16 branches also have the fix backported.
