### ISSUE TITLE
Top/Bottom margin does not work properly when dock position is Top/Bottom

### ISSUE THREAD

**Issue by vjcagay** [passingthru67/workspaces-to-dock#56]
So there is an option to position the workspaces dock to place them on right/left/top/bottom. When you specify a top or bottom margin it works as long as the workspaces are left or right. But if set to top/bottom and you put a top/bottom margin, the margins are applied on the wrong sides of the workspaces dock. Instead of being applied as top/bottom margin it is applied as the left/right margin instead.

![screenshot from 2016-03-20 03-40-40](https://cloud.githubusercontent.com/assets/3283683/13900939/93867a70-ee4d-11e5-8d73-0b7b5e85680c.png)

In the picture above, I tried applying 25% top margin, but instead the dock's position moved to the right, when it should have moved downwards.

**Comment by passingthru67** [comment]
Apologies for the confusion. I failed to re-label the preferences to indicate that the top/bottom margins of the dock (originally intended for left/right dock positions) change to left/right margins for the top/bottom dock positions.

**Comment by passingthru67** [comment]
The latest master code addresses this issue.
