### ISSUE TITLE
Bottom padding

### ISSUE THREAD

**Issue by zagortenay333** [passingthru67/workspaces-to-dock#58]
I get this weird padding when the dock is on the left/right:
![screenshot from 2016-03-30 22-08-07](https://cloud.githubusercontent.com/assets/11144630/14155874/ecb319e0-f6c3-11e5-96c1-c3316331181d.png)

Happens with both these options:
![screenshot from 2016-03-30 22-03-06](https://cloud.githubusercontent.com/assets/11144630/14155736/415515f8-f6c3-11e5-90fc-9b5ae7cd8098.png)

**Comment by passingthru67** [comment]
Are you using a different theme other than the default Adwaita?

**Comment by zagortenay333** [comment]
Well, clearly I am, but it happens with all themes.

**Comment by zagortenay333** [comment]
I'm on shell `3.20` btw. If I remember correctly I used to have it i `3.18` as well

**Comment by passingthru67** [comment]
I was having a brain freeze moment. I couldn't make sense of what you were describing until I read the title of this issue again. Now it makes sense.

**Comment by zagortenay333** [comment]
Lol, sorry.

**Comment by passingthru67** [comment]
The latest code in master fixes this issue. I will eventually backport the fix to Gnome 3.18, 3.16. and 3.14.

**Comment by zagortenay333** [comment]
Nice.
