### ISSUE TITLE
Gnome 3.20

### ISSUE THREAD

**Issue by franlinux** [passingthru67/workspaces-to-dock#59]
Workspaces-to-dock work in gnome 3.20?

Thanks !

**Comment by passingthru67** [comment]
I plan on updating the master branch to Gnome 3.20 this week. In the mean time, changing the metadata.json shell-version from 3.18 to 3.20 should do the trick.

**Comment by franlinux** [comment]
Thanks ! Great extension!

**Comment by passingthru67** [comment]
Version 36 for Gnome 3.20 is available at https://extensions.gnome.org
