### ISSUE TITLE
Delay when hiding

### ISSUE THREAD

**Issue by zagortenay333** [passingthru67/workspaces-to-dock#60]
When you are in the overview and you click a window to get out, there is a slight delay before the workspaces start to hide. Basically, they seem to wait until you are fully out of the overview.

Without the extension, the workspaces start hiding concurrently with the rest of the screen.

**Comment by passingthru67** [comment]
There's been some recent changes that could possible afffect what you're describing .. so I need to know if this is an install from the master branch (Gnome 3.20) or a previous version (Gnome 3.??)

**Comment by zagortenay333** [comment]
Srry, completely forgot bout that :smile: ... Might wanna consider adding a template for issues.

It's from master, gnome 3.20.

**Comment by passingthru67** [comment]
This is now fixed in the latest master branch. Also, thanks for the suggestion regarding an issues template. I didn't know Github had such a feature.

**Comment by zagortenay333** [comment]
Nice!
