### ISSUE TITLE
Switching Workspaces with Nautilus Windows

### ISSUE THREAD

**Issue by PowerOfM** [passingthru67/workspaces-to-dock#62]
The favourite shortcuts panel of Workspaces-to-Dock works great when switching between multiple instances of an application on different workspaces, except with Nautilus.

Steps to reproduce:
1. In Workspace 1: Open Nautilus
2. Switch to Workspace 2: Click on Nautilus icon in shortcuts panel (does not switch to workspace 1)

Trying the above steps with, say terminal, and the workspaces switch from 2 to 1 correctly. (I'm running GNOME Shell 3.20.2 on Arch with a dual monitor setup).

Also, middle-clicking (scroll-wheel click) on an icon will launch a new instance of all other apps, except Nautilus, which does some weird things. For example, in the above scenario, while in workspace 2, middle-clicking on the Nautilus icon will actually switch to workspace 1, show the current Nautilus window, and then show a 'working' cursor for ~10s. No new window is spawned. 

It's just a minor problem because every other app that I tried works fine.

**Comment by passingthru67** [comment]
@PowerOfM, I believe Item #2 (Nautilus middle-click) is a Gnome Shell / Nautilus bug. Nautilus middle-click acts weird even with the Gnome Shell dash.

As for Item #1 (favorite shortcut icon for Nautilus not switching back to workspace 1), I haven't been able to duplicate. Anything different about you setup that I should be aware of while troubleshooting?

**Comment by passingthru67** [comment]
@PowerOfM, It seems that using Nautilus to show the desktop is what causes Item #1 issue above. I'll look into a workaround.

**Comment by PowerOfM** [comment]
@passingthru67 Yea, I was suspecting something about the way Nautilus is embedded into Gnome is the problem. However, both middle-clicking and workspace switching works fine in the [Dash-to-Dock](https://github.com/micheleg/dash-to-dock) extension for Nautilus.

I tried looking around their source code and came across this function:
`// Filter out unnecessary windows, for instance
// nautilus desktop window.
function getInterestingWindows(app) {
    return app.get_windows().filter(function(w) {
        return !w.skip_taskbar;
    });
}`

I haven't ever worked with Gnome code before, so not sure if this is helpful. [Here's the full code](https://github.com/micheleg/dash-to-dock/blob/master/appIcons.js#L514), including their implementation of [cycleThroughWindows()](https://github.com/micheleg/dash-to-dock/blob/master/appIcons.js#L412) that I mentioned in issue 63.

**Comment by passingthru67** [comment]
@PowerOfM .. Yes, Dash-to-Dock has a workaround for the problem. I've just implemented it and should be pushing an update very soon.

**Comment by passingthru67** [comment]
@PowerOfM, Would you try the latest master branch and see if Issue 1 above (Nautilus workspace switching) is fixed?

**Comment by PowerOfM** [comment]
@passingthru67 You are amazing. Both this and cycling windows done beautifully! Thank you so much!!
