### ISSUE TITLE
Focusing an App with Multiple Instances

### ISSUE THREAD

**Issue by PowerOfM** [passingthru67/workspaces-to-dock#63]
If there is an app with multiple instances in the background (not minimized but blocked by some full-screen/larger window), clicking on the icon in the shortcuts panel makes all instances come to the foreground. I was wondering if you could add an option to cycle between each window (i.e. clicking once focuses last-used window, clicking a second time focuses the 2nd-last-used window, and so on). This already happens when you click the icon multiple times, it is just that first click rushing all windows to the foreground that is a bit annoying. 

Perhaps future options to consider: Dash-to-Dock has alternative options, like instead of cycling through windows, toggling the minimized state of each window. (I realize that you made workspaces-to-dock work nicely along side dash-to-dock, but now with the amazing show-partial-fixed option, I would really love to just use this extension).

Thanks for all your amazing work on this extension!

**Comment by passingthru67** [comment]
I hadn't noticed that before. I'll look into why it's doing it.

**Comment by passingthru67** [comment]
@PowerOfM, I'll see about adding some of those features. The favorite panel is slowly evolving into a full-fledged dash-like panel.

**Comment by passingthru67** [comment]
@PowerOfM, Would you try the latest master branch and see if the problem is fixed?

**Comment by PowerOfM** [comment]
@passingthru67 Fixed! Great work!
