### ISSUE TITLE
Add option to hide "window" that appears when switching workspace

### ISSUE THREAD

**Issue by nunocastromartins** [passingthru67/workspaces-to-dock#64]
First of all, thank you for the awesome extension!

I've recently discovered the option to show the workspaces' dock when switching workspace. While I think it is really nice, I also believe that having two windows popping up whenever I switch workspace is bad; the native window is useless:

![middle-workspace-switcher](https://cloud.githubusercontent.com/assets/8314616/15832305/84ea2eee-2c19-11e6-974a-2291783adc10.png)

Would it be possible to hide Gnome's native workspace switching window, so that only the dock appears?

Do you know of any other extension that achieves this? I browsed through the extensions at https://extensions.gnome.org but couldn't find any. In either case, I believe it would make sense to add the option to this extension.

Once again, thank you for the amazing work!

**Comment by passingthru67** [comment]
@nunocastromartins, I have some other commitments right now, but, I'll see about adding that option in the near future.

**Comment by nunocastromartins** [comment]
Any progress on this? 😄
Are you still planning on adding this option?

**Comment by passingthru67** [comment]
I apologize for the delay but my time has become extremely limited lately. Actually, it's been several years now that I find myself lacking time for much else other than work and a 'honey do' list of home improvement projects. Nevertheless, I still plan on adding this feature.

**Comment by nunocastromartins** [comment]
Completely understandable!
I'd ask you for pointers on how to do this and do it myself, but I'm very much in the same boat regarding work.

Best of luck! I'll eagerly await.

**Comment by nunocastromartins** [comment]
Found this: https://extensions.gnome.org/extension/959/disable-workspace-switcher-popup/
Just leaving it here as reference, when you get the time. :-)

**Comment by balderclaassen** [comment]
And another one [](https://extensions.gnome.org/extension/758/no-workspace-switcher-popup/)

**Comment by passingthru67** [comment]
The latest commits add the option to hide the workspace switcher popup.
