### ISSUE TITLE
No autohiding by context menus getting displayed in the workspaces-dock area

### ISSUE THREAD

**Issue by fb87** [passingthru67/workspaces-to-dock#65]
When a part of context menus or mouseover popups gets displayed in the workspaces-dock area, the workspaces-dock gets hidden in autohide-mode. This should not be the case. Would be nice if someone can fix this. Many thanks for the extension!

**Comment by passingthru67** [comment]
It's a feature left over from a time when the gnome message tray was located at the bottom of the screen. Popup context menus from the message tray or the desktop (i.e. when Nautilus is used to display desktop icons) were difficult to interact with when the dock was visible. I'll update things to ignore popups by default but leave an option in the preferences for those who may still need this feature.

**Comment by fb87** [comment]
Nice, thanks!
