### ISSUE TITLE
Autohide on empty workspace

### ISSUE THREAD

**Issue by miguelcarax** [passingthru67/workspaces-to-dock#67]
I miss a "Hide" option at Beheviour > What should we do with the dock when not dodging windows?
Thanks!

**Comment by miguelcarax** [comment]
NVM: I disable Intellihide option and works fine now

**Comment by filtration** [comment]
> NVM: I disable Intellihide option and works fine now

This does not hide the top bar at all. I vote to have an option to allow autohide on empty workspaces.
