### ISSUE TITLE
Visible when autohide & intellihide are disabled

### ISSUE THREAD

**Issue by jsnj** [passingthru67/workspaces-to-dock#68]
If autohide & intellihide are disabled, the workspaces/dock should only appear in overview. Instead, it stays visible on top of open windows and won't disappear until the shell is restarted. Having it only appear in overview is useful for users who only want the extension as a dash replacement(when favorites are shown) since it requires less mouse/touchpad movement to change to a new workspace and open a favorite app.

**Comment by passingthru67** [comment]
That's an interesting use of the extension. I'll see what I can do to remedy this behavior.

**Comment by jsnj** [comment]
A workaround is setting the pressure threshold to 1000 which effectively disables autohide and allows the dock to only be seen in overview.

**Comment by passingthru67** [comment]
Just uploaded the fix in master.
