### ISSUE TITLE
Option for showing this on other sides of the screen

### ISSUE THREAD

**Issue by rugk** [passingthru67/workspaces-to-dock#69]
Especially in a multi-monitor setup it may be useful to show the dock on the bottom or top, so you can use your primary monitor if you have another monitor attached to the left/right.

Of course also "right" should be possible.

**Comment by passingthru67** [comment]
Workspaces-To-Dock versions for Gnome 3.16, 3.18, and 3.20 already do this. What version of Gnome are you running? Also, what version of Workspaces-To-Dock extension?

**Comment by rugk** [comment]
I use the one published at https://extensions.gnome.org. I could not find any about window where the exact version number is given.

**Comment by passingthru67** [comment]
Ahhah! There are many current features that I haven't backported to Gnome 3.14 yet. Between my day job and other home improvement projects, I don't really have time to test and maintain the extension for all the former versions of Gnome. Any chance you will upgrade to a newer Gnome version soon?

**Comment by rugk** [comment]
> Any chance you will upgrade to a newer Gnome version soon?

If there is  a new Debian release... :smile:

**Comment by rugk** [comment]
But this feature is not such important for me personally, so if you say it is already implemented and available in newer versions, you can close this issue if you want.
