### ISSUE TITLE
Dock vanishes when dragging windows between workspaces

### ISSUE THREAD

**Issue by etm** [passingthru67/workspaces-to-dock#77]
###Linux Distribution version
fedora

###Gnome Shell version
3.22

###Extension version or branch
40

###Description of the problem

When "Dock is fixed and always visible", after dragging a window between workspaces
changes to overview and the dock vanishes. The dock should not vanish.

###Steps to reproduce the problem

Set "Dock is fixed and always visible".
Drag windows between workspaces.

**Comment by passingthru67** [comment]
This issue should be fixed now for both the master branch and gnome 3.22 branch

**Comment by etm** [comment]
I can confirm it works. Thanks.
