### ISSUE TITLE
Dock steals mouse clicks

### ISSUE THREAD

**Issue by etm** [passingthru67/workspaces-to-dock#78]
###Linux Distribution version
fedora

###Gnome Shell version
3.22

###Extension version or branch
40

###Description of the problem

When "Dock is fixed and always visible", all mouse clicks to the area where the dock is behind a fullscreen application are "stolen" by the dock.

###Steps to reproduce the problem

* Set "Dock is fixed and always visible"
* Set "Extend the height of the dock to fill the screen"
* Open am movie in VLC, go to fullscreen
* Try to change the volume with the mouse (the dock is behind these controls, the dock is not visible)

This can be reproduced with any application that supports fullscreen, e.g. with a gnome-terminal it is not possible to move the scrollbar with the mouse in fullscreen mode.

**Comment by passingthru67** [comment]
The latest commits to the master branch should fix this issue.

**Comment by etm** [comment]
Works like a charm. Thank you.
