### ISSUE TITLE
Autohide causes some extra cpu usage

### ISSUE THREAD

**Issue by materemias** [passingthru67/workspaces-to-dock#84]
###Linux Distribution version
Arch upto date

###Gnome Shell version
3.22

###Extension version or branch
latest from gnome.org (39)

###Description of the problem
if I enable Autohide gnome-shell cpu usage goes up to 10-15% compared to 3-5% when disabled

###Steps to reproduce the problem
enable Autohide.

**Comment by balderclaassen** [comment]
@materemias Is this still happening ? 
For me Autohide doesn't seem to affect CPU and gnome-shell stays rather consistent at about 5% regardless of the setting.
