### ISSUE TITLE
selecting monitor has no effect under wayland

### ISSUE THREAD

**Issue by emerge-e-world** [passingthru67/workspaces-to-dock#85]
###Linux Distribution version
Arch Linux x86_64

###Gnome Shell version
3.22.3

###Extension version or branch
v40

###Description of the problem
When running under wayland with a multi-monitor setup, selecting a different monitor to show the dock on has no effect. The dock is always schown on the primary display.

###Steps to reproduce the problem
- Run GNOME on wayland
- open the extensions settings
- select a different monitor under "General -> Position -> Show the dock on the following monitor".

**Comment by passingthru67** [comment]
The latest commits in the master branch should fix this issue.

**Comment by emerge-e-world** [comment]
I tested the latest master branch, the commit fixes the issue for me. Thanks!
