### ISSUE TITLE
Move/resize with gTile or ShellTile ignored in Thumbnails

### ISSUE THREAD

**Issue by ddnexus** [passingthru67/workspaces-to-dock#89]
###Linux Distribution version
Ubuntu-Gnome

###Gnome Shell version
3.20 - Wayland

###Extension version or branch
latest

###Description of the problem
Thumbnails don't get refreshed when you move/resize a window with gTile or ShellTile; they keep showing the previous state of the workspace (with the window(s) in the old position/size)

###Steps to reproduce the problem
Use any of the 2 mentioned extensions to move/reshape a window.

###Workaroud
Go to overview, move the un-refreshed window to another desktop and back in, and the thumbnail will get refreshed.

**Comment by passingthru67** [comment]
The latest commits in the master branch (Gnome 3.24) should fix this issue. I plan on backporting it to Gnome 3.22 also.
