### ISSUE TITLE
Cannot move Workspaces to Dock to the secondary monitor under gnome 3.24

### ISSUE THREAD

**Issue by Pre-Z** [passingthru67/workspaces-to-dock#94]
###Linux Distribution version
Arch Linux 64 bit

###Gnome Shell version
3.24 on Xorg and the issue also persist on Wayland

###Extension version or branch
41

###Description of the problem
With multimonitor setup Workspaces to Dock always stays on the main screen regardless of the chosen monitor number under the Position section of the extension's General settings.

###Steps to reproduce the problem
Make the following configuration with two monitors:
- set the main monitor for the left side
- Configure Workspaces to Dock at the General tab under Position:
  ~ Show the dock on the following monitor (if attached) -> set to 1
  ~ Show the dock at the following screen position -> set to Right

###Result
Workspaces to Dock remains on the right side of the primary monitor blocking mouse to pass through to the second monitor.

###Expected result
Workspaces to Dock should go to the secondary monitor to the very right side of it. Workspaces to Dock only should appear on the primary monitor if the secondary one is disconnected.

**Comment by passingthru67** [comment]
The latest commits in the master branch should fix this issue.
