### ISSUE TITLE
Dock does not appear while specific preferences are set

### ISSUE THREAD

**Issue by GoodMirek** [passingthru67/workspaces-to-dock#95]
### Linux Distribution version
Fedora Core 26 Alpha

### Gnome Shell version
gnome-shell-3.24.1-1.fc26.x86_64

### Extension version or branch
The one currently available via E.G.O. (https://extensions.gnome.org).
I have not found a way to display extension version in neither E.G.O. page nor the extension settings dialog.

### Description of the problem
If I check checkbox of both options:
Behavior --> Miscellaneous Options --> Disable scroll when dock is hidden to prevent workspace switching
and
Behavior --> Autohide Options --> Require pressure to show the dock
then the dock does not appear while applying pressure to the edge of the screen. Though it is possible to display the dock with shortcut.
While only one of the options is activated it works like a charm.

### Steps to reproduce the problem
Dock is located on right edge of the screen.
Single monitor setup - external monitor connected to laptop. Internal monitor is disabled in Gnome prefs.
Check the checkboxes mentioned in the description above. Try to display the dock by moving cursor with a mouse to the right edge and behind (the pressure).
Happens both in Gnome on Xorg and Gnome on Wayland.

**Comment by passingthru67** [comment]
I'm not able to duplicate the issue. Could you try installing from Github? Since you're using Gnome 3.24, download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r). This way you get the latest enhancements and bug fixes.

**Comment by passingthru67** [comment]
Any update on this issue?

**Comment by GoodMirek** [comment]
I have upgraded the extension via E.G.O. today and the issue reproduces
under both Wayland and Xorg.

Then, I have tried your instructions, downloaded master from github and
replaced the existing plugin with the extracted content of the archive. i
did not delete the old plugin, just copied the new files over the old files.
I did it under Xorg session and restarted Gnome Shell with Alt+F2 -> r.
After the restart the issue still persists in Xorg. After logout/login
under wayland, the issue persists under wayland too.

I have the extension installed together with Michele's "Dash to Dock". I
have also noticed under wayland (did not try under Xorg) that with the
master branch installed the Dash-to-Dock integration does not work any
longer - while I am hovering over "Dash to Dock", the "Workspaces to Dock"
does not show. I have doublechecked that the integration option is switched
on.

Offtopic: If you add an about dialog with flattr button like Michele has
then I will be happy to flattr the extension regularly.

Mirek Svoboda | +1 (845) 584-1854  | Skype: xsvobo10

**Comment by passingthru67** [comment]
Please export your settings by opening a terminal and typing "dconf dump /org/gnome/shell/extensions/workspaces-to-dock/". Then, copy/paste the results here. I'll need them to duplicate your environment.

**Comment by GoodMirek** [comment]
Please find the result below. Please let me know what else can I do.

dconf dump /org/gnome/shell/extensions/workspaces-to-dock/
[/]
primary-monitor=0
intellihide-option=0
shortcuts-panel-show-running=true
dashtodock-hover=true
use-pressure-speed-limit=true
customize-height=true
disable-scroll=false
quick-show-timeout=500.0
animation-time=0.0
show-shortcuts-panel=true
shortcuts-panel-show-window-count-indicators=true
hide-delay=0.5
pressure-threshold=100.0
customize-height-option=1
require-pressure-to-show=true
shortcuts-panel-popupmenu-arrow-at-top=true
shortcuts-panel-show-places=false
toggle-overview=true
quick-show-on-workspace-change=true
scroll-with-touchpad=true
background-opacity=0.48999999999999999
top-margin=0.14999999999999999
bottom-margin=0.14999999999999999
show-delay=0.10000000000000001



Mirek Svoboda | +1 (845) 584-1854  | Skype: xsvobo10

**Comment by passingthru67** [comment]
Thanks. I'm trying to duplicate the issue without having to install Fedora 26 alpha. BTW, are there any other extensions installed other than Dash-to-Dock?

**Comment by GoodMirek** [comment]
There are following extensions installed and enabled:

   - AlternateTab  by fmuellner
   - Clipboard Indicator  by Tudmotu
   - Dash to Dock  by michele_g
   - EasyScreenCast  by IacopoDeeNosee
   - Pixel Saver  by deadalnix
   - TopIcons Plus  by phocean

There are a few more installed and disabled, which came with FC26 and
cannot be uninstalled from E.G.O. webpage.

The issue persists even when I disable all Gnome extensions, but Workspaces
to Dock; tested under Wayland.

Regarding my setup, I use a notebook with closed lid and with external
monitor, keyboard and mouse. Effectively, I use only one monitor (2560 x
1080).

I tried to make a screencast, to be sure we are aligned what the issue is
and how it looks like. It is split into two videos, as video recording
stopped at the change of extension preferences. While recording the second
part, it stopped recording without any apparent reason. It is probably a
different, not related issue, I am letting you know just in case.

Also, it seems that "Hide delay" option of "Workspaces to Dock" has no
effect in my environment or I do not understand when the delay should
occur. It is probably a different issue too.

Mirek Svoboda | +1 (845) 584-1854 <(845)%20584-1854>  | Skype: xsvobo10

>

**Comment by GoodMirek** [comment]
[Uploading Videos.zip…]()

**Comment by GoodMirek** [comment]
[Videos.zip](https://github.com/passingthru67/workspaces-to-dock/files/1053962/Videos.zip)

**Comment by GoodMirek** [comment]
Note: I am 99% sure that the issue happened also before I have upgraded from FC25 to FC26 Alpha. I just thought the issue could have disappeared with the upgrade, so I waited with report until after then.

**Comment by GoodMirek** [comment]
I have /org/gnome/desktop/wm/preferences/focus-mode set to 'sloppy'.
I tried to check it back to default value 'click', it did not help as the issue persisted.

**Comment by passingthru67** [comment]
From the video and your description, it sounds like the pressure threshold stops working when the 'Disable scroll when dock is hidden' option is selected. Anyway, I'll be digging into the issue further.

**Comment by passingthru67** [comment]
One thing I'd like you to change in the dock preferences ..

Uncheck the  'Limit pressure sense to slow mouse speeds' option. It's found in the Autohide Options section under the Behavior tab.

**Comment by GoodMirek** [comment]
I have unchecked the 'Limit pressure sense to slow mouse speeds' option and
at the same time checked "Disable scroll when dock is hidden to prevent
workspace switching".
Now, it works sometimes (once out of 3-10 attempts), more often at high
mouse speeds.

Mirek Svoboda | +1 (845) 584-1854  | Skype: xsvobo10

**Comment by passingthru67** [comment]
I was finally able to duplicate your issue. It looks like when the dock animation is set to 0ms (like your setup), the pressure barrier doesn't have enough time to get created. The easy fix is to limit the dock animation time to a minimum of 50ms, otherwise it requires the 1px border (present when the scroll is enabled) to trigger the dock.

I'll look into another solution, but in the mean time, if you need the scroll to be disabled, you'll have to set your animation time to a value greater than 0ms. BTW, the animation time is set in the Timing Options section of the Behavior tab.

**Comment by passingthru67** [comment]
I have uploaded a fix I need you to test on your unit.

Please download the fix-animation branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/fix-animation.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r).

Let me know if this fixes the issue for you.

**Comment by nunocastromartins** [comment]
Hi! I've noticed the same issue.
I haven't tested your branch; just wanted to add that the issue also happens when the "Enable animations" option is disabled in Gnome's Tweak Tool; this option:

![pref](https://user-images.githubusercontent.com/8314616/28025728-186ea076-658c-11e7-87a0-6d5e70521294.png)

I hope the fix still works. :-)

**Comment by passingthru67** [comment]
The previous fix still had some issues so I uploaded a new fix. Anyone still having problems when animation is turned off (or set low/fast) should download the 'fix-show-hide-animation' branch and test again.

**Comment by passingthru67** [comment]
Here goes yet another 'fix' attempt. I've committed a new branch that I hope fixes the dock show/hide issues when animation timing is adjusted or turned off. Anybody interested in testing this, please download the 'fix-show-hide' branch and let me know if the problem goes away.

**Comment by passingthru67** [comment]
The fix is now in the master branch. Closing this issue.

**Comment by GoodMirek** [comment]
Thanks @passingthru67 !
I am sorry I have never came back to this issue and did not make the test you have asked for.

**Comment by passingthru67** [comment]
@GoodMirek: Not a problem. I appreciate the issue report and the feedback. Every bit helps.

**Comment by GoodMirek** [comment]
@passingthru67 Is the fix available from E.G.O. already? I have tried to switch off the visible edge and the original problem re-appeared.

**Comment by passingthru67** [comment]
Not yet. I'll be submitting a new version to E.G.O. for review soon. I'm trying to squash as many bugs before I do.

**Comment by GoodMirek** [comment]
I have pulled the master and it works fine for me in Fedora
26, gnome-shell-3.24.3-2.fc26.x86_64

Mirek Svoboda | +1 (845) 584-1854  (Timezone UTC+2) | Skype: xsvobo10

**Comment by passingthru67** [comment]
@GoodMirek: Glad to hear that. The newest version is under review at E.G.O. It should be available there soon.
