### ISSUE TITLE
Feature Request: change rouneded corners to straight corners option?

### ISSUE THREAD

**Issue by jessedubord** [passingthru67/workspaces-to-dock#97]
###Linux Distribution version
Ubuntu GNOME 17.04

###Gnome Shell version
3.24.1

###Extension version or branch
master

###Description
For appearance purposes, it would be nice to have an option in the "General" section that allows users to switch between rounded corners for the workspaces section to straight corners for the more boxy, clean-cut look.

**Comment by passingthru67** [comment]
The latest commits add this option.
