### ISSUE TITLE
Set workspaces thumbnails always in center

### ISSUE THREAD

**Issue by alex285** [passingthru67/workspaces-to-dock#98]
when we set full width, both on vertical or horizontal position, is it possible to have an option for workspaces thumbnails to be aligned on center?

that is similar as without setting a full width, but full width feels more natural with the workspaces bar to fill all the space

**Comment by passingthru67** [comment]
That's certainly a possibility in the future.

As a workaround, select the customize height of dock -> autosize and center option. Then edit the workspaces-to-dock.css as follows ..

#workspacestodockContainerWrapper {
    background-color: rgba(10,10,10,0.8);
}

This creates a dark background (as opposed to transparent) that extends the full length/height of the screen. The dock is centered in front of the dark background region.

**Comment by passingthru67** [comment]
This gives the allusion of an extended dock with the workspaces/favorites centered.

**Comment by passingthru67** [comment]
To add to the allusion, you can set the transparency of the dock background to 0.

**Comment by alex285** [comment]
@passingthru67 
```
#workspacestodockContainerWrapper {
background-color: rgba(10,10,10,0.8);
}
```
that wont work with Adapta Shell theme ..in fact extend setting the height to fill the screen wont work with Adapta correctly either. it will leave some empty space on the bottom

**Comment by passingthru67** [comment]
I'll have to check out Adapta and see what they're doing different.

**Comment by passingthru67** [comment]
Found the issue with Adapta. Adapta's gnome-shell.css has a 32px bottom margin set. Find the /usr/share/themes/Adapta/gnome-shell/gnome-shell.css and remark out the margin-bottom entry as follows ..

.workspace-thumbnails, .workspace-thumbnails-left { 
    visible-width: 32px; 
    spacing: 12px; 
    /* margin-bottom: 32px;*/ 
    padding: 12px; 
    border: none; 
    border-radius: 0; 
    background-color: rgba(19, 25, 28, 0.01); 
    color: #CFD8DC; }

**Comment by alex285** [comment]
@passingthru67 thanks for the quick fix! but perhaps i better wait for make the center thing code side, because i often update Adapta and extensions, so i really dont want to edit css each time!

if that specific Adapta CSS will cause an issue, we should open a bug there. I guess Adapta uses this margin to dont collide with Dash To Panel though

oh on a sidenote, since that is my first issue, excellent extension! a must have to me together with Dash To Panel!

**Comment by passingthru67** [comment]
@alex285: I just committed code to the 'feature-dock-centering' branch that provides advanced centering options. You should now be able to extend the dock and still keep the thumbnails centered. Let me know if it works like you expect.

BTW, anyone using the Adapta theme should copy the workspaces-to-dock.css in the workspaces-to-dock@passingthru67.gmail.com/themes/adapta/ folder to their Adapta (or one of it's derivatives) theme directory (/usr/share/themes/**Adapta**/gnome-shell/extensions/workspaces-to-dock/). This is just a temporary fix until the Adapta theme is updated to work with the css changes in workspaces-to-dock.

**Comment by alex285** [comment]
@passingthru67 yeap totally! i even tubed it! https://youtu.be/NZXFylIuwFM

a small recommendation is if you can keep the default Shell 3.26 behavior, and as extra only add appIcons and push sensitivity! this extension is pretty neat overall, but they default settings are scary :)
