### ISSUE TITLE
missing thumbnail - wayland weirdness

### ISSUE THREAD

**Issue by etm** [passingthru67/workspaces-to-dock#99]
###Linux Distribution version
Fedora 25, 26

###Gnome Shell
3.22.x, 3.24.x

###Extension version or branch
master

###Description of the problem
newly opened applications have a "missing icon" (white sheet of paper) thumbnail.

THIS ONLY APPLIES TO WAYLAND SESSIONS, but it affects all versions of gnome-shell and wayland so far.

###Steps to reproduce the problem
when opening an application (e.g. a terminal), the thumbnail shown for this application is a "missing icon" (white sheet of paper). When moving the mouse to the thumbnail and moving it off again, the thumbnail becomes completely empty (just the border and the gradient).

BUT: when moving the application to a different workspace, the correct icon suddenly appears.  

![screenshot from 2017-05-23 10-57-50](https://cloud.githubusercontent.com/assets/241775/26346525/c71eb40a-3fa6-11e7-8ead-335438b66be2.png)

The screenshot shows both states: the first thumbnail is a terminal where the thumbnail has already been "touched" by the mouse, the second icon is a nautilus.

**Comment by passingthru67** [comment]
The issue isn't isolated to Workspaces-to-Dock. Even Gnome Shell's Window List extension has this problem. I suspect it's an upstream bug or maybe just Wayland growing pains.

**Comment by passingthru67** [comment]
Ok, I was wrong. It's a timing issue in how the extension monitors newly created windows and not a bug in Wayland. The new window is added to the workspace before the compositor is aware of it. Anyway, checkout the latest commit in the master branch for the fix.

**Comment by etm** [comment]
Fixed. Thanks.
